import React,{useEffect,useMemo,useRef,useState}from'react';
import {loadMyNotifications,markNotificationRead,NotificationRow}from'../../services/notifications';
import {supabase,supabaseEnabled}from'../../supabase';

interface NotificationsProps{onBack:()=>void;onOpenBill:(billId:string)=>void;}
const localDateKey=(value:string)=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dateLabel=(value:string)=>new Date(`${value}T00:00:00`).toLocaleDateString('en-IN',{year:'numeric',month:'long',day:'numeric'});
const Notifications:React.FC<NotificationsProps>=({onBack,onOpenBill})=>{
  const[items,setItems]=useState<NotificationRow[]>([]);const[loading,setLoading]=useState(true);const swipeStart=useRef<number|null>(null);
  const load=async()=>{try{setItems(await loadMyNotifications())}catch{setItems([])}finally{setLoading(false)}};
  useEffect(()=>{void load();let channel:any=null;void(async()=>{if(!supabaseEnabled||!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;channel=supabase.channel(`employee-notifications-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`recipient_id=eq.${user.id}`},()=>void load()).subscribe()})();return()=>{if(channel)supabase?.removeChannel(channel)}},[]);
  const markRead=async(n:NotificationRow)=>{if(n.read_at)return;const stamp=new Date().toISOString();setItems(p=>p.map(x=>x.id===n.id?{...x,read_at:stamp}:x));try{await markNotificationRead(n.id)}catch{setItems(p=>p.map(x=>x.id===n.id?{...x,read_at:n.read_at}:x))}};
  const open=async(n:NotificationRow)=>{await markRead(n);if((n.notification_type==='monthly_bill_published'||n.notification_type==='additional_bill_published')&&typeof n.payload?.bill_id==='string')onOpenBill(n.payload.bill_id)};
  const groups=useMemo(()=>{const map=new Map<string,NotificationRow[]>();items.forEach(n=>{const key=localDateKey(n.created_at);const row=map.get(key)||[];row.push(n);map.set(key,row)});return Array.from(map.entries())},[items]);
  return <section className="w-full min-w-0"><div className="mb-5 flex items-center gap-3"><button type="button" onClick={onBack} className="rounded-lg border px-3 py-2 text-sm font-semibold text-gray-700">← Back</button><div><h2 className="text-2xl font-bold text-gray-800">Notifications</h2><p className="text-sm text-gray-500">{items.filter(n=>!n.read_at).length} unread · {items.length} history</p></div></div>{loading?<p className="rounded-lg bg-gray-50 p-4 text-sm text-gray-500">Loading notification history…</p>:items.length===0?<p className="rounded-lg border bg-gray-50 p-5 text-sm text-gray-500">No notifications yet.</p>:<div className="space-y-5">{groups.map(([key,rows])=><div key={key}><h3 className="mb-2 text-sm font-bold text-gray-700">{dateLabel(key)}</h3><div className="space-y-2">{rows.map(n=><div key={n.id} onTouchStart={e=>{swipeStart.current=e.changedTouches[0]?.clientX??null}} onTouchEnd={e=>{const start=swipeStart.current;swipeStart.current=null;if(start!==null&&(start-e.changedTouches[0].clientX)>60)void markRead(n)}} className={`rounded-xl border p-4 transition ${n.read_at?'bg-white':'bg-primary-50'}`}><div className="flex items-start justify-between gap-3"><button type="button" onClick={()=>void open(n)} className="min-w-0 flex-1 text-left"><div className="flex items-center gap-2"><span className="font-semibold text-gray-800 break-words">{n.title}</span>{!n.read_at&&<span className="shrink-0 rounded-full bg-red-600 px-2 py-0.5 text-[10px] font-bold text-white">NEW</span>}</div><p className="mt-1 break-words text-sm text-gray-600">{n.message}</p><p className="mt-2 text-[11px] text-gray-400">{new Date(n.created_at).toLocaleString('en-IN')}</p>{(n.notification_type==='monthly_bill_published'||n.notification_type==='additional_bill_published')&&typeof n.payload?.bill_id==='string'&&<p className="mt-2 text-xs font-semibold text-primary-700">Tap to open bill</p>}</button>{!n.read_at&&<button type="button" onClick={()=>void markRead(n)} className="shrink-0 rounded-lg border px-2 py-1 text-xs font-semibold text-gray-600">Read</button>}</div></div>)}</div></div>)}</div>}<p className="mt-4 text-xs text-gray-400">Swipe a notification left to mark it as read. Read notifications remain in daily history.</p></section>;
};
export default Notifications;
