import React,{useEffect,useState}from'react';
import {supabase,supabaseEnabled}from'../../supabase';
import {loadMyNotifications,markNotificationRead,NotificationRow}from'../../services/notifications';
interface NotificationBellProps{onViewAll?:()=>void;onOpenBill?:(billId:string)=>void;}
const NotificationBell:React.FC<NotificationBellProps>=({onViewAll,onOpenBill})=>{
  const[items,setItems]=useState<NotificationRow[]>([]);const[open,setOpen]=useState(false);
  const load=async()=>{try{setItems(await loadMyNotifications())}catch(e){console.warn('Notification load failed.',e)}};
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),15000);let channel:ReturnType<NonNullable<typeof supabase>['channel']>|undefined;if(supabaseEnabled&&supabase)channel=supabase.channel('employee-notifications').on('postgres_changes',{event:'*',schema:'public',table:'notifications'},()=>void load()).subscribe();return()=>{window.clearInterval(timer);if(channel)void channel.unsubscribe()}},[]);
  const unread=items.filter(n=>!n.read_at).length;
  const openNotification=async(n:NotificationRow)=>{if(!n.read_at){try{await markNotificationRead(n.id)}catch{}setItems(prev=>prev.map(x=>x.id===n.id?{...x,read_at:new Date().toISOString()}:x))}if(n.notification_type==='monthly_bill_published'&&typeof n.payload?.bill_id==='string'){setOpen(false);onOpenBill?.(n.payload.bill_id);return}};
  return <div className="relative shrink-0"><button type="button" aria-label="Notifications" onClick={()=>setOpen(v=>!v)} className="relative flex h-11 w-11 touch-manipulation items-center justify-center rounded-full bg-gray-100 text-xl hover:bg-gray-200">🔔{unread>0&&<span className="absolute -right-0.5 -top-0.5 flex h-5 min-w-5 items-center justify-center rounded-full bg-red-600 px-1 text-[10px] font-bold text-white">{unread>9?'9+':unread}</span>}</button>{open&&<div className="absolute right-0 top-[calc(100%+8px)] z-[60] box-border w-[calc(100vw-24px)] max-w-[360px] min-w-0 overflow-hidden rounded-xl border border-gray-200 bg-white shadow-xl"><div className="flex min-w-0 items-center justify-between gap-2 border-b px-4 py-3"><span className="min-w-0 break-words font-bold text-gray-800">Notifications</span><span className="shrink-0 text-xs text-gray-500">{unread} unread</span></div><div className="max-h-80 min-w-0 overflow-y-auto">{items.length===0?<p className="p-4 text-sm text-gray-500">No notifications.</p>:items.slice(0,20).map(n=><button key={n.id} type="button" onClick={()=>void openNotification(n)} className={`block w-full min-w-0 border-b px-4 py-3 text-left ${n.read_at?'bg-white':'bg-primary-50'}`}><div className="break-words whitespace-normal font-semibold text-gray-800">{n.title}</div><div className="mt-1 break-words whitespace-normal text-sm text-gray-600">{n.message}</div><div className="mt-1 break-words text-[11px] text-gray-400">{new Date(n.created_at).toLocaleString()}</div></button>)}</div>{onViewAll&&<button type="button" onClick={()=>{setOpen(false);onViewAll()}} className="w-full border-t px-4 py-3 text-center text-sm font-semibold text-primary-700">View all notifications</button>}</div>}</div>;
};
export default NotificationBell;
