import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../../context/AuthContext';
import{useData}from'../../context/DataContext';
import{formatDate}from'../../utils/helpers';
import{supabase}from'../../supabase';
import{calculateEmployeeFoodContribution}from'../../utils/employeeFoodContribution';

type HistoryItem={code:string;name:string;quantity:number;unitPrice:number;source:'employee'|'guest'|'admin';employeeUnitPrice:number};
type HistoryOrder={id:string;date:string;status:'active'|'cancelled';items:HistoryItem[];employeeAmount:number};
type ExtraRow={amount:number;description:string;contribution_eligible?:boolean;employee_food_amount?:number|null};
const OrderCalendar:React.FC=()=>{
 const{user}=useAuth();const{menuItems,prices}=useData();const[selectedDate,setSelectedDate]=useState<string|null>(null);const[orders,setOrders]=useState<HistoryOrder[]>([]);const[extras,setExtras]=useState<Record<string,ExtraRow[]>>({});
 const getFallbackPrice=(code:string)=>menuItems.find(item=>item.itemCode===code)?.unitPrice??(code in prices?prices[code as keyof typeof prices]:0);
 const load=async()=>{if(!user||!supabase)return;try{const{data:profile,error:profileError}=await supabase.from('profiles').select('id').or(`employee_code.eq.${user.id},sr_number.eq.${user.id}`).maybeSingle();if(profileError)throw profileError;if(!profile)return;const{data:orderRows,error:orderError}=await supabase.from('orders').select('id,employee_id,ordered_for,status,created_at,employee_contribution_percentage,employee_food_amount,order_items(item_code,item_name,quantity,unit_price,item_source,guest_name)').eq('employee_id',profile.id).order('ordered_for',{ascending:false}).order('created_at',{ascending:false});if(orderError)throw orderError;
 const mapped:HistoryOrder[]=(orderRows||[]).map((row:any)=>{const grouped=new Map<string,HistoryItem>();const contribution=Number(row.employee_contribution_percentage||0);(row.order_items||[]).forEach((item:any)=>{const quantity=Number(item.quantity||0);if(quantity<=0)return;const source:HistoryItem['source']=item.item_source==='guest'?'guest':item.item_source==='admin'?'admin':'employee';const code=String(item.item_code);const unitPrice=Number(item.unit_price??getFallbackPrice(code));const employeeUnitPrice=source==='guest'?unitPrice:calculateEmployeeFoodContribution(unitPrice,contribution).employeeAmount;const key=`${source}|${code}`;const existing=grouped.get(key);if(existing)existing.quantity+=quantity;else grouped.set(key,{code,name:item.item_name||code,quantity,unitPrice,source,employeeUnitPrice})});const items=Array.from(grouped.values());const calculatedEmployee=items.filter(item=>item.source!=='guest').reduce((sum,item)=>sum+item.quantity*item.employeeUnitPrice,0);return{id:String(row.id),date:String(row.ordered_for),status:row.status==='cancelled'?'cancelled':'active',items,employeeAmount:row.employee_food_amount==null?calculatedEmployee:Number(row.employee_food_amount)};}).filter(order=>order.items.length>0);
 const{data:adjustments,error:adjustmentError}=await supabase.from('employee_adjustments').select('adjustment_date,amount,description,contribution_eligible,employee_food_amount').eq('employee_id',profile.id);if(adjustmentError)throw adjustmentError;const extraMap:Record<string,ExtraRow[]>={};(adjustments||[]).forEach((item:any)=>{const date=String(item.adjustment_date);(extraMap[date]||(extraMap[date]=[])).push({amount:Number(item.amount||0),description:String(item.description||'').trim(),contribution_eligible:Boolean(item.contribution_eligible),employee_food_amount:item.employee_food_amount==null?null:Number(item.employee_food_amount)})});setOrders(mapped);setExtras(extraMap)}catch(error){console.warn('Could not load member daily activity history.',error)}};
 useEffect(()=>{if(!user||!supabase)return;let alive=true;const refresh=async()=>{if(!alive)return;await load()};void refresh();const channel=supabase.channel(`employee-history-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'orders'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'employee_adjustments'},refresh).subscribe();const timer=window.setInterval(refresh,10000);return()=>{alive=false;window.clearInterval(timer);void channel.unsubscribe()}},[user]);
 const activityDates=useMemo(()=>Array.from(new Set([...orders.map(order=>order.date),...Object.keys(extras)])).sort((a,b)=>b.localeCompare(a)).slice(0,15),[orders,extras]);const dayOrders=useMemo(()=>{const map=new Map<string,HistoryOrder[]>();orders.forEach(order=>{const list=map.get(order.date)||[];list.push(order);map.set(order.date,list)});return map},[orders]);
 const dayItems=(date:string,source:HistoryItem['source'])=>{const grouped=new Map<string,HistoryItem>();(dayOrders.get(date)||[]).forEach(order=>order.items.forEach(item=>{if(item.source!==source)return;const existing=grouped.get(item.code);if(existing)existing.quantity+=item.quantity;else grouped.set(item.code,{...item})}));return Array.from(grouped.values())};
 const employeeFoodTotal=(date:string)=>dayItems(date,'employee').reduce((sum,item)=>sum+item.quantity*item.employeeUnitPrice,0);const adminOrderTotal=(date:string)=>dayItems(date,'admin').reduce((sum,item)=>sum+item.quantity*item.employeeUnitPrice,0);const guestTotal=(date:string)=>dayItems(date,'guest').reduce((sum,item)=>sum+item.quantity*item.unitPrice,0);const extraPayableTotal=(date:string)=>(extras[date]||[]).reduce((sum,row)=>sum+(row.contribution_eligible?Number(row.employee_food_amount??row.amount):Number(row.amount||0)),0);const dayTotal=(date:string)=>employeeFoodTotal(date)+adminOrderTotal(date)+guestTotal(date)+extraPayableTotal(date);const cancelled=(date:string)=>{const list=dayOrders.get(date)||[];return list.some(order=>order.status==='cancelled')&&!list.some(order=>order.status==='active')};
 const renderDetails=(date:string)=><div className="mt-2 rounded-lg border bg-gray-50 p-4"><div className="flex items-center justify-between gap-3"><h4 className="font-bold text-gray-800">Details for {date}</h4><button type="button" aria-label="Close details" onClick={event=>{event.stopPropagation();setSelectedDate(null)}} className="rounded px-2 py-1 text-gray-500">✕</button></div><div className="mt-3 space-y-4">{(['employee','guest','admin']as const).map(source=>{const items=dayItems(date,source);if(!items.length)return null;const title=source==='employee'?'MEMBER ORDER':source==='guest'?'GUEST ORDER':'ADMIN ORDERED';const total=source==='employee'?employeeFoodTotal(date):source==='admin'?adminOrderTotal(date):guestTotal(date);return <section key={source}><h5 className="mb-2 font-bold text-gray-800">{title}</h5><div className="space-y-2">{items.map(item=><div key={item.code} className="flex justify-between gap-3 border-b pb-2 text-sm"><span>{item.name} × {item.quantity}</span><span>₹{((source==='guest'?item.unitPrice:item.employeeUnitPrice)*item.quantity).toFixed(2)}</span></div>)}</div><div className="mt-2 flex justify-between text-sm font-semibold"><span>{source==='guest'?'Guest Total':source==='admin'?'Admin Order Total':'Food Total'}</span><span>₹{total.toFixed(2)}</span></div></section>})}{(extras[date]||[]).length>0&&<section><h5 className="mb-2 font-bold text-gray-800">ADMIN ADDED</h5><div className="space-y-2">{(extras[date]||[]).map((row,index)=><div key={`${date}-extra-${index}`} className="rounded border-b pb-2 text-sm"><div className="flex justify-between gap-3"><span>Admin Added</span><span>₹{(row.contribution_eligible?Number(row.employee_food_amount??row.amount):Number(row.amount||0)).toFixed(2)}</span></div>{row.description&&<div className="mt-1 break-words text-xs text-gray-500">Reason: {row.description}</div>}</div>)}</div></section>}{cancelled(date)&&<div className="rounded-md bg-red-50 p-3 font-semibold text-red-700">Order cancelled. The cancelled activity remains in history and is not counted as an active current order.</div>}<div className="flex justify-between border-t pt-3 font-bold"><span>DAY TOTAL</span><span>₹{dayTotal(date).toFixed(2)}</span></div></div></div>;
 return <div className="w-full min-w-0 rounded-lg bg-white p-3 shadow-md sm:p-6"><div className="mb-4"><h3 className="text-xl font-bold text-gray-800">Last 15 Days – Daily Activity History</h3><p className="mt-1 text-sm text-gray-500">Select a date to view member orders, guest orders and admin activity for that day.</p></div>{activityDates.length===0?<p className="rounded-md bg-gray-50 p-4 text-sm text-gray-500">No orders or admin changes yet.</p>:<div className="grid grid-cols-1 gap-2">{activityDates.map(date=>{const employeeItems=dayItems(date,'employee');const guestItems=dayItems(date,'guest');const adminItems=dayItems(date,'admin');const extra=extraPayableTotal(date);const hasActivity=employeeItems.length>0||guestItems.length>0||adminItems.length>0||extra!==0;const summary=[employeeItems.length?`Member Order • ${employeeItems.map(item=>`${item.name} × ${item.quantity}`).join(', ')}`:'',guestItems.length?`Guest Order • ${guestItems.map(item=>`${item.name} × ${item.quantity}`).join(', ')}`:'',adminItems.length?`Admin Ordered • ${adminItems.map(item=>`${item.name} × ${item.quantity}`).join(', ')}`:'',extra!==0?`Admin Added ₹${extra.toFixed(2)}`:''].filter(Boolean).join(' • ');return <div key={date} className="min-w-0"><button type="button" onClick={()=>setSelectedDate(selectedDate===date?null:date)} className={`flex w-full min-w-0 items-center justify-between gap-3 rounded-lg border p-3 text-left ${selectedDate===date?'border-primary-500 bg-primary-50':'hover:bg-gray-50'}`}><div className="min-w-0"><div className="font-semibold text-gray-800">{date}</div><div className="truncate text-sm text-gray-600">{hasActivity?summary:'No activity'}{cancelled(date)&&<span className="ml-2 font-semibold text-red-600">Cancelled</span>}</div></div><span className="shrink-0 font-semibold text-primary-700">₹{dayTotal(date).toFixed(2)}</span></button>{selectedDate===date&&renderDetails(date)}</div>})}</div>}<p className="mt-5 text-xs text-gray-400">Today is {formatDate(new Date())}. Previous dates are view-only.</p></div>;
};export default OrderCalendar;
