import React,{useEffect,useState}from'react';
import{DataProvider}from'./context/DataContext';
import{AuthProvider,useAuth}from'./context/AuthContext';
import Login from'./components/auth/Login';
import CanteenOnboarding from'./components/auth/CanteenOnboarding';
import EmployeeDashboard from'./components/employee/EmployeeDashboard';
import AdminDashboard from'./components/admin/AdminDashboard';
import SuperAdminDashboard from'./components/admin/SuperAdminDashboard';
import ContactUs from'./components/admin/ContactUs';
import InitialPasswordChange from'./components/auth/InitialPasswordChange';
import{CanteenAccessState,loadCanteenAccessState}from'./services/subscriptionPlatform';

const SplashScreen:React.FC=()=> <div className="flex min-h-screen flex-col items-center justify-center bg-white"><span className="text-4xl font-extrabold text-primary-700">Go Canteen</span><span className="mt-2 text-[9px] font-medium text-black">Powered by Alien 1729</span></div>;

const SubscriptionRestrictedScreen:React.FC<{userRole:'admin'|'employee';access:CanteenAccessState|null;verificationError:boolean;checking:boolean;onRetry:()=>void;onLogout:()=>void}>=({userRole,access,verificationError,checking,onRetry,onLogout})=>{const status=access?.status;const statusLabel=status?status.replace('_',' ').toUpperCase():'UNKNOWN';const title=verificationError?'Subscription Status Could Not Be Verified':status==='suspended'?'Canteen Subscription Suspended':status==='expired'?'Subscription Expired':status==='unassigned'?'Subscription Not Assigned':'Subscription Access Restricted';const description=verificationError?'Your subscription access could not be verified at the moment. Normal canteen operations are temporarily restricted. Please try again.':status==='suspended'?'Your canteen subscription is currently suspended.':status==='expired'?'Your subscription period has expired.':status==='unassigned'?'No subscription is currently assigned to this canteen.':'Your subscription access is currently restricted.';return <div className="flex min-h-screen w-full overflow-y-auto overflow-x-hidden bg-gray-50 px-4 py-6 sm:items-center sm:py-8"><main className="mx-auto flex w-full max-w-md flex-col items-center rounded-2xl bg-white p-6 text-center shadow-sm sm:p-8"><img src="/logo.svg" alt="GoCanteen" className="h-20 w-20 rounded-2xl object-contain" /><h1 className="mt-5 text-xl font-extrabold text-gray-900 sm:text-2xl">{title}</h1><p className="mt-3 text-sm leading-6 text-gray-600">{description}</p>{status&&<div className="mt-5 w-full rounded-xl border border-gray-200 bg-gray-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-gray-500">Current Status</p><p className="mt-1 text-lg font-extrabold text-gray-800">{statusLabel}</p>{status==='trial'&&access?.subscription?.payment_status==='pending'&&<p className="mt-1 text-xs text-gray-500">Your trial is active; payment status is shown separately.</p>}</div>}<div className="mt-6 flex w-full flex-col gap-3"><button type="button" disabled={checking} onClick={onRetry} className="min-h-12 w-full rounded-xl bg-primary-600 px-4 py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{checking?'Checking…':'Retry Verification'}</button><button type="button" onClick={onLogout} className="min-h-12 w-full rounded-xl border border-gray-300 bg-white px-4 py-3 font-bold text-gray-700 hover:bg-gray-50">Logout</button></div><p className="mt-5 text-xs leading-5 text-gray-500">If the problem continues, you can logout and sign in again or contact GoCanteen support.</p></main></div>};
const AppContent:React.FC=()=>{const{user,loading}=useAuth();if(loading)return <SplashScreen/>;if(!user)return <Login/>;if(user.role==='admin'&&user.adminRole==='super_admin')return <SuperAdminDashboard/>;if(user.role==='admin'&&user.needsCanteenSetup)return <CanteenOnboarding/>;if(user.role==='employee'&&user.isFirstLogin)return <InitialPasswordChange/>;if(user.role==='employee')return <EmployeeDashboard/>;if(user.role==='admin')return <AdminDashboard/>;return <Login/>};

const App:React.FC=()=>{const[splash,setSplash]=useState(true);useEffect(()=>{const timer=window.setTimeout(()=>setSplash(false),1000);return()=>window.clearTimeout(timer)},[]);return <AuthProvider><DataProvider>{splash?<SplashScreen/>:<SubscriptionAccessBoundary><AppContent/></SubscriptionAccessBoundary>}</DataProvider></AuthProvider>};
export default App;

const SubscriptionAccessBoundary:React.FC<{children:React.ReactNode}>=({children})=>{const{user,logout}=useAuth();const[access,setAccess]=useState<CanteenAccessState|null>(null);const[checking,setChecking]=useState(false);const[verificationError,setVerificationError]=useState(false);const[autoAttempted,setAutoAttempted]=useState(false);const shouldCheck=Boolean(user?.canteenId&&((user.role==='admin'&&!user.needsCanteenSetup)||(user.role==='employee'&&!user.isFirstLogin)));const check=async()=>{if(!shouldCheck||!user?.canteenId||checking)return;setChecking(true);setVerificationError(false);try{const fresh=await loadCanteenAccessState(user.canteenId);setAccess(fresh);if(!fresh.allowed&&fresh.reason==='verification_error')setVerificationError(true)}catch(e){console.warn('Subscription access verification failed.',e);setAccess(prev=>prev||{allowed:false,status:null,subscription:null,reason:'verification_error'});setVerificationError(true)}finally{setChecking(false)}};useEffect(()=>{setAccess(null);setVerificationError(false);setAutoAttempted(false)},[user?.canteenId,user?.role,user?.needsCanteenSetup,user?.isFirstLogin]);useEffect(()=>{if(!shouldCheck||autoAttempted)return;setAutoAttempted(true);void check()},[shouldCheck,autoAttempted]);if(!shouldCheck)return <>{children}</>;if(checking&&!access)return <SplashScreen/>;if(!access)return <SplashScreen/>;if(access.allowed)return <>{children}</>;return <SubscriptionRestrictedScreen userRole={user?.role==='admin'?'admin':'employee'} access={access} verificationError={verificationError} checking={checking} onRetry={()=>void check()} onLogout={()=>void logout()}/>;};