import { supabase, supabaseEnabled } from '../supabase';

export interface BundleMember { id:string; full_name:string; mobile_number:string|null; }
export interface BundleCategory { id:string; name:string; }
export interface BundleMenuItem { item_code:string; item_name:string; unit_price:number; category_id:string|null; }
export interface BundleItemSnapshot { menu_item_code:string; item_name:string; quantity:number; unit_price:number; }
export interface BundleAssignment { id:string; member_id:string; bundle_id:string; bundle_type:'monthly'|'weekly'; period_start:string; period_end:string; billing_period:string; price_snapshot:number; status:'active'|'cancelled'|'expired'|'deleted'; bundle_name_snapshot:string; bundle_description_snapshot:string; category_name_snapshot:string|null; category_id?:string|null; items_snapshot:BundleItemSnapshot[]; member_name_snapshot:string|null; member_mobile_snapshot:string|null; created_at:string; }
export interface WeeklyBundleReadiness { member_id:string; member_name:string; bundle_total:number; bundle_count:number; }
export interface MonthlyBundleSummary { member_id:string; member_name:string; bundle_total:number; bundle_count:number; bundles:Array<{name:string;amount:number;billing_period:string;items:BundleItemSnapshot[]}>; }

const requireClient=()=>{if(!supabaseEnabled||!supabase)throw new Error('Supabase is not enabled.');return supabase;};
const mapAssignment=(row:any,categoryId?:string|null):BundleAssignment=>({...row,price_snapshot:Number(row.price_snapshot||0),items_snapshot:Array.isArray(row.items_snapshot)?row.items_snapshot:[],category_id:categoryId||null});
export async function loadBundleMembers():Promise<BundleMember[]>{const db=requireClient();const{data,error}=await db.from('profiles').select('id,full_name,mobile_number').eq('role','employee').eq('status','active').order('full_name');if(error)throw error;return(data||[]) as BundleMember[];}
export async function loadBundleCategories():Promise<BundleCategory[]>{const db=requireClient();const{data,error}=await db.from('menu_categories').select('id,name').eq('active',true).order('name');if(error)throw error;return(data||[]) as BundleCategory[];}
export async function loadBundleMenuItems():Promise<BundleMenuItem[]>{const db=requireClient();const{data,error}=await db.from('menu_prices').select('item_code,item_name,unit_price,category_id').eq('active',true).eq('archived',false).order('item_name');if(error)throw error;return(data||[]).map((r:any)=>({...r,unit_price:Number(r.unit_price||0)}));}
export async function loadBundleAssignments():Promise<BundleAssignment[]>{const db=requireClient();const{data,error}=await db.from('member_bundle_assignments').select('id,member_id,bundle_id,period_start,period_end,billing_period,price_snapshot,status,bundle_name_snapshot,bundle_description_snapshot,category_name_snapshot,items_snapshot,member_name_snapshot,member_mobile_snapshot,created_at').order('period_start',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;const rows=data||[];const bundleIds=Array.from(new Set(rows.map((r:any)=>r.bundle_id).filter(Boolean)));const categoryMap=new Map<string,string|null>();if(bundleIds.length){const{data:bundles,error:bundleError}=await db.from('bundles').select('id,category_id').in('id',bundleIds);if(bundleError)throw bundleError;(bundles||[]).forEach((b:any)=>categoryMap.set(b.id,b.category_id||null));}return rows.map((r:any)=>mapAssignment(r,categoryMap.get(r.bundle_id)||null));}
export async function createBundleAssignment(input:{member_id:string;name:string;description:string;bundle_type:'monthly'|'weekly';category_id:string|null;items:Array<{menu_item_code:string;quantity:number}>;price:number;period_start:string;period_end:string}){const db=requireClient();const{data,error}=await db.rpc('create_bundle_assignment',{p_member_id:input.member_id,p_name:input.name,p_description:input.description,p_bundle_type:input.bundle_type,p_category_id:input.category_id,p_items:input.items,p_price:input.price,p_period_start:input.period_start,p_period_end:input.period_end});if(error)throw error;return data as BundleAssignment;}
export async function updateBundleAssignment(input:{assignment_id:string;name:string;description:string;bundle_type:'monthly'|'weekly';category_id:string|null;items:Array<{menu_item_code:string;quantity:number}>;price:number;period_start:string;period_end:string;status:string}){const db=requireClient();const{data,error}=await db.rpc('update_bundle_assignment',{p_assignment_id:input.assignment_id,p_name:input.name,p_description:input.description,p_bundle_type:input.bundle_type,p_category_id:input.category_id,p_items:input.items,p_price:input.price,p_period_start:input.period_start,p_period_end:input.period_end,p_status:input.status});if(error)throw error;return data as BundleAssignment;}
export async function deleteBundleAssignment(id:string,reason:string){const db=requireClient();const{data,error}=await db.rpc('delete_bundle_assignment',{p_assignment_id:id,p_reason:reason});if(error)throw error;return data as BundleAssignment;}
export async function loadWeeklyBundleReadiness(start:string,end:string):Promise<WeeklyBundleReadiness[]>{const db=requireClient();const{data,error}=await db.rpc('get_weekly_bundle_billing',{p_week_start:start,p_week_end:end});if(error)throw error;return(data||[]).map((r:any)=>({...r,bundle_total:Number(r.bundle_total||0),bundle_count:Number(r.bundle_count||0)}));}
export async function loadMonthlyBundleSummary(month:number,year:number):Promise<MonthlyBundleSummary[]>{const db=requireClient();const{data,error}=await db.rpc('get_monthly_bundle_summary',{p_month:month,p_year:year});if(error)throw error;return(data||[]).map((r:any)=>({...r,bundle_total:Number(r.bundle_total||0),bundle_count:Number(r.bundle_count||0),bundles:Array.isArray(r.bundles)?r.bundles:[]}));}
export async function loadMemberBundlesForDate(memberId:string,date:string):Promise<BundleAssignment[]>{const db=requireClient();const{data,error}=await db.from('member_bundle_assignments').select('id,member_id,bundle_id,period_start,period_end,billing_period,price_snapshot,status,bundle_name_snapshot,bundle_description_snapshot,category_name_snapshot,items_snapshot,member_name_snapshot,member_mobile_snapshot,created_at').eq('member_id',memberId).eq('status','active').lte('period_start',date).gte('period_end',date).order('created_at',{ascending:false});if(error)throw error;return(data||[]).map((r:any)=>mapAssignment(r));}
export async function loadAdminBundlesForDate(date:string):Promise<BundleAssignment[]>{const db=requireClient();const{data,error}=await db.from('member_bundle_assignments').select('id,member_id,bundle_id,period_start,period_end,billing_period,price_snapshot,status,bundle_name_snapshot,bundle_description_snapshot,category_name_snapshot,items_snapshot,member_name_snapshot,member_mobile_snapshot,created_at').eq('status','active').lte('period_start',date).gte('period_end',date).order('member_name_snapshot');if(error)throw error;return(data||[]).map((r:any)=>mapAssignment(r));}
export async function loadBillBundleLines(billIds:string[]){const db=requireClient();if(!billIds.length)return[];const{data,error}=await db.from('monthly_bill_bundle_lines').select('id,bill_id,assignment_id,bundle_name_snapshot,bundle_description_snapshot,bundle_type,period_start,period_end,amount,items_snapshot,member_name_snapshot,member_mobile_snapshot').in('bill_id',billIds).order('created_at');if(error)throw error;return(data||[]).map((r:any)=>({...r,amount:Number(r.amount||0),items_snapshot:Array.isArray(r.items_snapshot)?r.items_snapshot:[]}));}
