import { supabase, supabaseEnabled } from '../supabase';
export interface NotificationRow{id:string;recipient_id:string;notification_type:string;title:string;message:string;payload:Record<string,unknown>;read_at?:string|null;created_at:string;}
async function loadNotifications(unreadOnly=false):Promise<NotificationRow[]>{if(!supabaseEnabled||!supabase)return[];const all:NotificationRow[]=[];for(let from=0;;from+=1000){let query=supabase.from('notifications').select('*').order('created_at',{ascending:false}).range(from,from+999);if(unreadOnly)query=query.is('read_at',null);const{data,error}=await query;if(error)throw error;const rows=(data||[]) as NotificationRow[];all.push(...rows);if(rows.length<1000)break}return all;}
export async function loadMyNotifications():Promise<NotificationRow[]>{return loadNotifications(false);}
export async function loadMyUnreadNotifications():Promise<NotificationRow[]>{return loadNotifications(true);}
export async function markNotificationRead(id:string){if(!supabaseEnabled||!supabase)return;const{error}=await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);if(error)throw error;}
async function profileByEmployeeCode(employeeCode:string){const{data,error}=await supabase!.from('profiles').select('id').or(`employee_code.eq.${employeeCode},sr_number.eq.${employeeCode}`).maybeSingle();if(error)throw error;return data;}
const eventKeyFor=(type:string,message:string,payload:Record<string,unknown>)=>String(payload.event_key||`${type}:${String(payload.adjustment_id||payload.order_id||payload.payment_id||payload.bill_id||payload.date||message)}`);
export async function notifyEmployee(employeeId:string,title:string,message:string,type='admin_update',payload:Record<string,unknown>={}){if(!supabaseEnabled||!supabase)return;const eventKey=eventKeyFor(type,message,payload);const{error}=await supabase.rpc('create_member_notification',{p_recipient_id:employeeId,p_notification_type:type,p_title:title,p_message:message,p_payload:payload,p_event_key:eventKey});if(error)throw error;}
export async function notifyCanteenEmployees(title:string,message:string,type='admin_update',payload:Record<string,unknown>={}){if(!supabaseEnabled||!supabase)return;const eventKey=eventKeyFor(type,message,payload);const{error}=await supabase.rpc('notify_canteen_employees',{p_event_key:eventKey,p_notification_type:type,p_title:title,p_message:message,p_payload:payload});if(error)throw error;}
export async function notifyEmployeeByCode(employeeCode:string,title:string,message:string,type='admin_update',payload:Record<string,unknown>={}){if(!supabaseEnabled||!supabase)return;const profile=await profileByEmployeeCode(employeeCode);if(profile)await notifyEmployee(profile.id,title,message,type,payload);}
