import{AppLauncher}from'@capacitor/app-launcher';import{supabase,supabaseEnabled}from'../supabase';import{MonthlyBill,loadAdminBills}from'./monthlyBills';
export type PaymentStatus='unpaid'|'pending_verification'|'paid'|'not_received'|'rejected';
export interface BillPayment{id:string;bill_id:string;employee_id:string;amount:number;status:PaymentStatus;confirmed_at?:string|null;approved_at?:string|null;approved_by?:string|null;created_at:string;updated_at:string;payment_reference?:string|null;covered_through?:string|null;request_sequence?:number|null;}
export interface BillPaymentSummary{current_total:number;confirmed_received:number;pending_amount:number;outstanding_balance:number;current_payment_id:string|null;}
export async function loadMyBillPayments(billIds:string[]){if(!supabaseEnabled||!supabase||!billIds.length)return[]as BillPayment[];const{data,error}=await supabase.from('bill_payments').select('*').in('bill_id',billIds).order('created_at',{ascending:false});if(error)throw error;return(data||[]).map((r:any)=>({...r,amount:Number(r.amount),request_sequence:r.request_sequence==null?null:Number(r.request_sequence)}))}
export async function loadBillPaymentSummary(billId:string):Promise<BillPaymentSummary>{if(!supabaseEnabled||!supabase)throw new Error('Supabase is not enabled.');const{data,error}=await supabase.rpc('get_bill_payment_summary',{p_bill_id:billId});if(error)throw error;const row=Array.isArray(data)?data[0]:data;return{current_total:Number(row?.current_total||0),confirmed_received:Number(row?.confirmed_received||0),pending_amount:Number(row?.pending_amount||0),outstanding_balance:Number(row?.outstanding_balance||0),current_payment_id:row?.current_payment_id||null}}
export async function confirmBillPayment(paymentId:string){if(!supabaseEnabled||!supabase)throw new Error('Supabase is not enabled.');const{data,error}=await supabase.rpc('confirm_bill_payment',{p_payment_id:paymentId});if(error)throw error;return data as BillPayment}
export async function loadPaymentsForMonth(month:number,year:number){if(!supabaseEnabled||!supabase)return[]as any[];const bills=await loadAdminBills(month,year);if(!bills.length)return[];const ids=bills.map(b=>b.id);const{data,error}=await supabase.from('bill_payments').select('*').in('bill_id',ids).order('created_at',{ascending:false});if(error)throw error;const payments=(data||[]).map((p:any)=>({...p,amount:Number(p.amount),request_sequence:p.request_sequence==null?null:Number(p.request_sequence)}));return bills.flatMap((b:any)=>payments.filter((p:any)=>p.bill_id===b.id).map((p:any)=>({...p,monthly_bills:b})));}
export async function approveBillPayment(paymentId:string){return setBillPaymentStatus(paymentId,'paid')}
export async function setBillPaymentStatus(paymentId:string,status:'paid'|'not_received'){if(!supabaseEnabled||!supabase)throw new Error('Supabase is not enabled.');const{data,error}=await supabase.rpc('set_bill_payment_status',{p_payment_id:paymentId,p_status:status});if(error)throw error;return data}

// UPI transaction references are constrained to a compact alphanumeric value.
// Preserve an existing batch reference when it can be represented safely;
// otherwise derive a deterministic reference from the unique payment id.
function buildUpiTransactionReference(bill:MonthlyBill,payment:BillPayment){const existing=(payment.payment_reference||'').replace(/[^A-Za-z0-9]/g,'');if(existing.length>0&&existing.length<=35)return existing;const month=String(bill.bill_month).padStart(2,'0');const paymentId=payment.id.replace(/[^A-Fa-f0-9]/g,'').slice(0,27);return`GC${bill.bill_year}${month}${paymentId}`}
function buildUpiTransactionNote(bill:MonthlyBill,payment:BillPayment){const monthName=new Date(bill.bill_year,bill.bill_month-1,1).toLocaleString('en-IN',{month:'short'});const batch=payment.request_sequence?` B${payment.request_sequence}`:'';return`GoCanteen ${monthName} ${bill.bill_year} Bill${batch}`.slice(0,50)}

export function buildUpiIntent(bill:MonthlyBill,payment:BillPayment){const payee=(bill.upi_id||'').trim();const name=(bill.upi_name||'').trim();const amount=Number(payment.amount);if(amount<=0)throw new Error('No payment amount is available for this request.');if(!payee)throw new Error('UPI payment details are not configured for this bill.');if(!name)throw new Error('UPI payee name is not configured for this bill.');const ref=buildUpiTransactionReference(bill,payment);const note=buildUpiTransactionNote(bill,payment);const params=new URLSearchParams({pa:payee,pn:name,am:amount.toFixed(2),cu:'INR',tr:ref,tn:note});const url=`upi://pay?${params.toString()}`;if(import.meta.env.DEV)console.debug('[GoCanteen] UPI intent',url);return url}
export async function openUpiPayment(bill:MonthlyBill,payment:BillPayment){const url=buildUpiIntent(bill,payment);try{const result=await AppLauncher.openUrl({url});if(result?.completed===false)throw new Error('No compatible UPI app is installed on this device.');return true}catch(error:any){if(error?.message?.includes('No compatible'))throw error;throw new Error('Could not open a compatible UPI payment app. Please install Google Pay, PhonePe, BHIM, or another UPI app and try again.')}}
