import{supabase,supabaseEnabled}from'../supabase';import{MonthlyBill}from'./monthlyBills';
export type PaymentStatus='unpaid'|'pending_verification'|'paid'|'not_received';
export interface BillPayment{id:string;bill_id:string;employee_id:string;amount:number;status:'pending_verification'|'paid'|'not_received';confirmed_at?:string|null;approved_at?:string|null;approved_by?:string|null;created_at:string;updated_at:string;}
export async function loadMyBillPayments(billIds:string[]){if(!supabaseEnabled||!supabase||!billIds.length)return[]as BillPayment[];const{data,error}=await supabase.from('bill_payments').select('*').in('bill_id',billIds);if(error)throw error;return(data||[]).map((r:any)=>({...r,amount:Number(r.amount)}))}
export async function confirmBillPayment(bill:MonthlyBill){if(!supabaseEnabled||!supabase)throw new Error('Supabase is not enabled.');const{data,error}=await supabase.rpc('confirm_bill_payment',{p_bill_id:bill.id});if(error)throw error;return data as BillPayment}
export async function loadPaymentsForMonth(month:number,year:number){if(!supabaseEnabled||!supabase)return[]as any[];const{data,error}=await supabase.from('bill_payments').select('*, monthly_bills!bill_payments_bill_id_fkey(id,bill_month,bill_year,total,published,profiles!monthly_bills_employee_id_fkey(employee_code,sr_number,full_name))').eq('monthly_bills.bill_month',month).eq('monthly_bills.bill_year',year).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function approveBillPayment(paymentId:string){if(!supabaseEnabled||!supabase)throw new Error('Supabase is not enabled.');const{data,error}=await supabase.rpc('approve_bill_payment',{p_payment_id:paymentId});if(error)throw error;return data}
export async function setBillPaymentStatus(paymentId:string,status:'paid'|'not_received'){if(!supabaseEnabled||!supabase)throw new Error('Supabase is not enabled.');const{data,error}=await supabase.rpc('set_bill_payment_status',{p_payment_id:paymentId,p_status:status});if(error)throw error;return data}
export function buildUpiIntent(bill:MonthlyBill){const payee=(bill.upi_id||'').trim();const name=(bill.upi_name||'GoCanteen').trim();const amount=Number(bill.total).toFixed(2);const ref=`GoCanteen-${bill.bill_year}-${String(bill.bill_month).padStart(2,'0')}-${bill.id.slice(0,8)}`;if(!payee)throw new Error('UPI payment details are not configured for this bill.');return`upi://pay?pa=${encodeURIComponent(payee)}&pn=${encodeURIComponent(name)}&am=${encodeURIComponent(amount)}&cu=INR&tn=${encodeURIComponent(ref)}&tr=${encodeURIComponent(ref)}`}
