import { supabase, supabaseEnabled } from '../supabase';
import { User, Order, Prices, MenuItem, DailyMenuItem } from '../types';

const defaultNames: Record<string,string> = { morningTea:'Morning Tea', lunchMeals:'Lunch: Meals', lunchEgg:'Lunch: Egg (add-on)', lunchFishMeat:'Lunch: Fish/Meat (add-on)', eveningTea:'Evening Tea' };
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const retainedOrderStart=()=>{const d=new Date();return localDate(new Date(d.getFullYear(),d.getMonth()-1,1))};
const retainedOrderEnd=()=>localDate(new Date());
const requireClient=()=>{if(!supabaseEnabled||!supabase)throw new Error('Supabase is not enabled.');return supabase};
const profileSelect='id,employee_code,sr_number,full_name,mobile_number,role,status,is_first_login,canteen_id';

const loadMemberLoginMode=async(profileRows:any[]):Promise<'sr'|'mobile'>=>{const client=requireClient();const canteenId=profileRows.find(p=>p?.canteen_id)?.canteen_id;if(!canteenId)return'sr';const{data,error}=await client.from('canteens').select('member_login_mode').eq('id',canteenId).maybeSingle();if(error)throw error;return data?.member_login_mode==='mobile'?'mobile':'sr'};
const mapUsers=(data:any[],memberLoginMode:'sr'|'mobile'):User[]=>data.map((p:any)=>({id:p.employee_code||p.sr_number||p.id,name:p.full_name||'',mobile:p.mobile_number||'',password:'',role:p.role,status:p.status||'active',isFirstLogin:Boolean(p.is_first_login),canteenId:p.canteen_id||undefined,memberLoginMode}));

export async function loadScopedUsers():Promise<User[]>{const client=requireClient();const{data,error}=await client.from('profiles').select(profileSelect);if(error)throw error;const mode=await loadMemberLoginMode(data||[]);return mapUsers(data||[],mode)}

export async function loadScopedOrders(profileRows?:any[]):Promise<Order[]>{const client=requireClient();const{data,error}=await client.from('orders').select('id,employee_id,ordered_for,status,created_at,updated_at,cancelled_at,order_source,guest_name,guest_count,guest_total,order_items(id,item_code,item_name,quantity,unit_price,line_total,item_source,guest_name)').gte('ordered_for',retainedOrderStart()).lte('ordered_for',retainedOrderEnd()).order('ordered_for',{ascending:false});if(error)throw error;const rows=profileRows||await client.from('profiles').select('id,employee_code,sr_number,mobile_number,canteen_id').then(r=>{if(r.error)throw r.error;return r.data||[]});const mode=await loadMemberLoginMode(rows);const byUuid=new Map(rows.map((p:any)=>[p.id,p]));return(data||[]).filter((o:any)=>o.status!=='cancelled').map((o:any)=>{const items:Record<string,boolean>={},itemQuantities:Record<string,number>={},itemPrices:Record<string,number>={},itemNames:Record<string,string>={},guestItems:Record<string,boolean>={},guestItemQuantities:Record<string,number>={},guestItemPrices:Record<string,number>={},guestItemNames:Record<string,string>={};(o.order_items||[]).forEach((i:any)=>{const q=Number(i.quantity);if(!Number.isFinite(q)||q<=0)return;const source=i.item_source==='guest'?'guest':o.order_source==='admin'?'admin':'employee';if(source==='guest'){guestItems[i.item_code]=true;guestItemQuantities[i.item_code]=q;guestItemPrices[i.item_code]=Number(i.unit_price);guestItemNames[i.item_code]=i.item_name||defaultNames[i.item_code]||i.item_code}else{items[i.item_code]=true;itemQuantities[i.item_code]=q;itemPrices[i.item_code]=Number(i.unit_price);itemNames[i.item_code]=i.item_name||defaultNames[i.item_code]||i.item_code}});const p:any=byUuid.get(o.employee_id);const displayId=mode==='mobile'&&p?.role==='employee'?p?.mobile_number||p?.employee_code||p?.sr_number||o.employee_id:p?.employee_code||p?.sr_number||o.employee_id;return{id:o.id,employeeId:displayId,date:o.ordered_for,items,itemQuantities,itemPrices,itemNames,guestItems,guestItemQuantities,guestItemPrices,guestItemNames,orderSource:o.order_source==='admin'?'admin':'employee',guestName:o.guest_name||undefined,guestCount:o.guest_count==null?undefined:Number(o.guest_count),guestTotal:Number(o.guest_total||0),status:'active',cancelledAt:o.cancelled_at||undefined};})}

export async function loadScopedMenu():Promise<{prices:Prices;menuItems:MenuItem[]}>{const client=requireClient();const base:Prices={morningTea:8,lunchMeals:40,lunchEgg:10,lunchFishMeat:25,eveningTea:8};const{data,error}=await client.from('menu_prices').select('item_code,item_name,unit_price,active,archived').order('item_code');if(error)throw error;const menuItems=(data||[]).map((r:any)=>{if(r.item_code in base)base[r.item_code as keyof Prices]=Number(r.unit_price);return{itemCode:r.item_code,itemName:r.item_name||defaultNames[r.item_code]||r.item_code,unitPrice:Number(r.unit_price),active:Boolean(r.active),archived:Boolean(r.archived)}});return{prices:base,menuItems}}
export async function loadScopedDailyMenu():Promise<DailyMenuItem[]>{const client=requireClient();const today=localDate();const d=new Date();const end=localDate(new Date(d.getFullYear(),d.getMonth(),d.getDate()+6));const{data,error}=await client.from('daily_menu').select('menu_date,item_code,item_name,unit_price,active').gte('menu_date',today).lte('menu_date',end).order('menu_date').order('item_code');if(error)throw error;return(data||[]).map((r:any)=>({menuDate:String(r.menu_date),itemCode:r.item_code,itemName:r.item_name||defaultNames[r.item_code]||r.item_code,unitPrice:Number(r.unit_price),active:Boolean(r.active)}))}
export async function loadScopedHolidays():Promise<string[]>{const client=requireClient();const{data,error}=await client.from('holidays').select('holiday_date').order('holiday_date');if(error)throw error;return(data||[]).map((r:any)=>String(r.holiday_date))}
export async function loadScopedData(){const client=requireClient();const{data:profiles,error:pe}=await client.from('profiles').select(profileSelect);if(pe)throw pe;const mode=await loadMemberLoginMode(profiles||[]);const users=mapUsers(profiles||[],mode);const[orders,menu,dailyMenus,holidays]=await Promise.all([loadScopedOrders(profiles||[]),loadScopedMenu(),loadScopedDailyMenu(),loadScopedHolidays()]);return{users,orders,prices:menu.prices,menuItems:menu.menuItems,dailyMenus,holidays}}
