import React,{createContext,useContext,ReactNode,useEffect,useRef,useState,useCallback}from'react';
import{User,Order,Prices,Status,MenuItem,DailyMenuItem}from'../types';
import{upsertOrder,saveMenuItem,saveHoliday,removeHoliday}from'../services/supabaseSync';
import{loadScopedData,loadScopedOrders,loadScopedUsers,loadScopedMenu,loadScopedDailyMenu,loadScopedHolidays}from'../services/supabaseData';
import{supabase,supabaseEnabled}from'../supabase';
import{ADMIN_USER_ID,DEFAULT_ADMIN_PASSWORD}from'../constants';
import{useAuth}from'./AuthContext';

interface DataContextType{users:User[];setUsers:React.Dispatch<React.SetStateAction<User[]>>;orders:Order[];setOrders:React.Dispatch<React.SetStateAction<Order[]>>;prices:Prices;setPrices:React.Dispatch<React.SetStateAction<Prices>>;menuItems:MenuItem[];setMenuItems:React.Dispatch<React.SetStateAction<MenuItem[]>>;dailyMenus:DailyMenuItem[];setDailyMenus:React.Dispatch<React.SetStateAction<DailyMenuItem[]>>;holidays:string[];setHolidays:React.Dispatch<React.SetStateAction<string[]>>;addHoliday:(date:string)=>Promise<void>;deleteHoliday:(date:string)=>Promise<void>;cloudBackupEnabled:boolean;cloudSyncing:boolean}
const DataContext=createContext<DataContextType|undefined>(undefined);
const initialUsers:User[]=[{id:ADMIN_USER_ID,name:'GoCanteen Administrator',mobile:'',password:DEFAULT_ADMIN_PASSWORD,role:'admin',status:'active' as Status,isFirstLogin:false,authProvider:'password',memberLoginMode:'sr'}];
const initialPrices:Prices={morningTea:8,lunchMeals:40,lunchEgg:10,lunchFishMeat:25,eveningTea:8};
const initialMenuItems:MenuItem[]=[{itemCode:'morningTea',itemName:'Morning Tea',unitPrice:8,active:true},{itemCode:'lunchMeals',itemName:'Lunch: Meals',unitPrice:40,active:true},{itemCode:'lunchEgg',itemName:'Lunch: Egg (add-on)',unitPrice:10,active:true},{itemCode:'lunchFishMeat',itemName:'Lunch: Fish/Meat (add-on)',unitPrice:25,active:true},{itemCode:'eveningTea',itemName:'Evening Tea',unitPrice:8,active:true}];

export const DataProvider:React.FC<{children:ReactNode}>=({children})=>{
 const{user:authUser,loading:authLoading}=useAuth();
 const[users,setUsers]=useState<User[]>(supabaseEnabled?[]:initialUsers),[orders,setOrders]=useState<Order[]>([]),[prices,setPrices]=useState<Prices>(initialPrices),[menuItems,setMenuItems]=useState<MenuItem[]>(supabaseEnabled?[]:initialMenuItems),[dailyMenus,setDailyMenus]=useState<DailyMenuItem[]>([]),[holidays,setHolidays]=useState<string[]>([]),[cloudSyncing,setCloudSyncing]=useState(false);
 const hydrated=useRef(false),hydrating=useRef(false),syncInFlight=useRef(false),refreshRequested=useRef(false),timer=useRef<number|undefined>(),realtimeTimer=useRef<number|undefined>();
 const tenantKey=authUser?.canteenId?`${authUser.id}:${authUser.canteenId}`:authUser?.id||'';
 const resetTenantState=useCallback(()=>{hydrated.current=false;hydrating.current=false;refreshRequested.current=false;setUsers(supabaseEnabled?[]:initialUsers);setOrders([]);setPrices(initialPrices);setMenuItems(supabaseEnabled?[]:initialMenuItems);setDailyMenus([]);setHolidays([])},[]);
 const markServerRefresh=useCallback(()=>{hydrating.current=true},[]);
 const hydrate=useCallback(async()=>{if(!supabaseEnabled||!supabase||authLoading||!authUser?.id||!authUser.canteenId)return;if(syncInFlight.current){refreshRequested.current=true;return}try{markServerRefresh();const cloud=await loadScopedData(authUser.canteenId);setUsers(cloud.users||[]);setOrders(cloud.orders||[]);setPrices(cloud.prices||initialPrices);setMenuItems(cloud.menuItems||[]);setDailyMenus(cloud.dailyMenus||[]);setHolidays(cloud.holidays||[])}catch(e){hydrating.current=false;console.warn('Supabase tenant-scoped load failed; keeping current state.',e)}finally{hydrated.current=true}},[authLoading,authUser?.id,authUser?.canteenId,markServerRefresh]);
 const refreshOrders=useCallback(async()=>{if(!authUser?.canteenId)return;try{markServerRefresh();setOrders(await loadScopedOrders(authUser.canteenId))}catch(e){hydrating.current=false;console.warn('Supabase tenant-scoped order refresh failed; keeping current orders.',e)}},[authUser?.canteenId,markServerRefresh]);
 const refreshTable=useCallback(async(table:string)=>{if(!authUser?.canteenId)return;try{if(table==='orders'){await refreshOrders();return}if(table==='profiles'){markServerRefresh();setUsers(await loadScopedUsers(authUser.canteenId));return}if(table==='menu_prices'){const menu=await loadScopedMenu(authUser.canteenId);markServerRefresh();setPrices(menu.prices);setMenuItems(menu.menuItems);return}if(table==='daily_menu'){markServerRefresh();setDailyMenus(await loadScopedDailyMenu(authUser.canteenId));return}if(table==='holidays'){markServerRefresh();setHolidays(await loadScopedHolidays(authUser.canteenId));return}}catch(e){hydrating.current=false;console.warn(`Supabase tenant-scoped ${table} refresh failed; keeping current state.`,e)}},[authUser?.canteenId,markServerRefresh,refreshOrders]);
 useEffect(()=>{resetTenantState();if(!authLoading&&authUser?.canteenId)void hydrate()},[tenantKey,authLoading,authUser?.canteenId,resetTenantState,hydrate]);
 useEffect(()=>{if(!supabaseEnabled||!supabase||authLoading||!authUser?.id||!authUser.canteenId)return;let disposed=false;const onFocus=()=>{if(!disposed)void hydrate()};const onVisibility=()=>{if(document.visibilityState==='visible'&&!disposed)void hydrate()};const scheduleRefresh=(table:string)=>{window.clearTimeout(realtimeTimer.current);realtimeTimer.current=window.setTimeout(()=>{if(!disposed)void refreshTable(table)},750)};const interval=window.setInterval(()=>{void refreshOrders()},30000);window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisibility);const channel=supabase.channel(`gocanteen-data-sync-${authUser.canteenId}`).on('postgres_changes',{event:'*',schema:'public',table:'profiles',filter:`canteen_id=eq.${authUser.canteenId}`},()=>scheduleRefresh('profiles')).on('postgres_changes',{event:'*',schema:'public',table:'orders',filter:`canteen_id=eq.${authUser.canteenId}`},()=>scheduleRefresh('orders')).on('postgres_changes',{event:'*',schema:'public',table:'menu_prices',filter:`canteen_id=eq.${authUser.canteenId}`},()=>scheduleRefresh('menu_prices')).on('postgres_changes',{event:'*',schema:'public',table:'daily_menu',filter:`canteen_id=eq.${authUser.canteenId}`},()=>scheduleRefresh('daily_menu')).on('postgres_changes',{event:'*',schema:'public',table:'holidays',filter:`canteen_id=eq.${authUser.canteenId}`},()=>scheduleRefresh('holidays')).subscribe();return()=>{disposed=true;window.clearInterval(interval);window.clearTimeout(realtimeTimer.current);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisibility);void channel.unsubscribe()}},[authLoading,authUser?.id,authUser?.canteenId,hydrate,refreshOrders,refreshTable]);
 useEffect(()=>{if(!supabaseEnabled||!hydrated.current||!authUser?.canteenId)return;if(hydrating.current){hydrating.current=false;return}window.clearTimeout(timer.current);timer.current=window.setTimeout(async()=>{if(syncInFlight.current)return;syncInFlight.current=true;setCloudSyncing(true);try{for(const order of orders){const mobileUser=users.find(u=>u.role==='employee'&&u.memberLoginMode==='mobile'&&u.mobile===order.employeeId);const syncOrder=mobileUser?{...order,employeeId:mobileUser.id}:order;await upsertOrder(syncOrder,prices)}for(const item of menuItems)await saveMenuItem(item)}catch(e){console.warn('Background Supabase sync failed.',e)}finally{syncInFlight.current=false;setCloudSyncing(false);if(refreshRequested.current){refreshRequested.current=false;void hydrate()}}},500);return()=>window.clearTimeout(timer.current)},[orders,prices,menuItems,users,authUser?.canteenId,hydrate]);
 const addHoliday=async(date:string)=>{await saveHoliday(date);setHolidays(prev=>prev.includes(date)?prev:[...prev,date])};
 const deleteHoliday=async(date:string)=>{await removeHoliday(date);setHolidays(prev=>prev.filter(d=>d!==date))};
 return <DataContext.Provider value={{users,setUsers,orders,setOrders,prices,setPrices,menuItems,setMenuItems,dailyMenus,setDailyMenus,holidays,setHolidays,addHoliday,deleteHoliday,cloudBackupEnabled:supabaseEnabled,cloudSyncing}}>{children}</DataContext.Provider>;
};
export const useData=()=>{const context=useContext(DataContext);if(!context)throw new Error('useData must be used within a DataProvider');return context};
