import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.0'
const corsHeaders={ 'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS' }
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json'}})
const normalizeMobile=(v:string)=>{const d=String(v||'').trim().replace(/[^0-9]/g,'');return /^91[6-9][0-9]{9}$/.test(d)?d.slice(-10):d}
const validMobile=(v:string)=>/^[6-9][0-9]{9}$/.test(v)
const internalEmail=(m:string)=>`${m}@gocanteen.local`
const validPassword=(v:string)=>typeof v==='string'&&v.length>=8&&v.length<=128
const BUSINESS_PERMISSIONS=['dashboard','members','orders','guest_orders','menu','bundles','daily_reports','monthly_reports','revenue','expenses','bills','payments','time_management','holidays']
const activeDuplicateMessage=(profile:any)=>{if(profile?.role==='employee')return'This mobile number is already registered as a Member in this Canteen. This Admin cannot be created.';if(profile?.role==='admin')return'This mobile number is already registered as an Admin in this Canteen. This Admin cannot be created.';return'This mobile number is already registered and cannot be used for a new Admin.'}
const safeAuthError=(error:any,fallback='Could not update Admin authentication.')=>{const message=String(error?.message||'').trim();if(!message)return fallback;if(/duplicate|already.*use|already.*registered|email.*exists/i.test(message))return 'This Mobile Number is already in use by another active account.';if(/password/i.test(message))return 'Could not update the Admin password. Please verify the password and try again.';if(/email/i.test(message))return 'Could not update the Admin login identity. Please verify the Mobile Number and try again.';return message}
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Method not allowed.'},405)
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{autoRefreshToken:false,persistSession:false}})
 const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return json({error:'Authentication required.'},401)
 const{data:{user:caller},error:callerError}=await admin.auth.getUser(token);if(callerError||!caller)return json({error:'Authentication required.'},401)
 const{data:callerProfile,error:callerProfileError}=await admin.from('profiles').select('id,role,admin_role,status,canteen_id').eq('id',caller.id).maybeSingle();if(callerProfileError)return json({error:callerProfileError.message},500)
 if(!callerProfile||callerProfile.role!=='admin'||callerProfile.status!=='active'||callerProfile.admin_role!=='owner'||!callerProfile.canteen_id)return json({error:'Only the Google Owner can manage Admin Roles.'},403)
 const{data:ownerCanteen}=await admin.from('canteens').select('id').eq('id',callerProfile.canteen_id).eq('owner_id',caller.id).maybeSingle();if(!ownerCanteen)return json({error:'Owner authorization required.'},403)
 let body:any;try{body=await req.json()}catch{return json({error:'Invalid request.'},400)}
 const action=String(body?.action||'list'),canteenId=callerProfile.canteen_id
 const audit=async(target:string|null,name:string,metadata:Record<string,unknown>={})=>{const{error}=await admin.from('admin_audit_log').insert({acting_admin_id:caller.id,target_admin_id:target,canteen_id:canteenId,action:name,metadata});if(error)throw error}
 if(action==='list'){
   const{data,error}=await admin.from('profiles').select('id,full_name,mobile_number,status,canteen_id,admin_role').eq('canteen_id',canteenId).eq('role','admin').in('admin_role',['staff_admin','master_admin']).order('full_name');if(error)return json({error:error.message},500)
   const ids=(data||[]).map(x=>x.id);const{data:perms,error:permError}=ids.length?await admin.from('admin_permissions').select('admin_id,permission,enabled').in('admin_id',ids).eq('canteen_id',canteenId):{data:[],error:null};if(permError)return json({error:permError.message},500);const grouped:Record<string,string[]>={};for(const p of perms||[]){if(BUSINESS_PERMISSIONS.includes(p.permission)&&p.enabled)(grouped[p.admin_id]??=[]).push(p.permission)}
   return json({staff:(data||[]).map(s=>({...s,permissions:[...new Set(grouped[s.id]||[])]}))})
 }
 if(action==='create'){
   const name=String(body?.name||'').trim(),mobile=normalizeMobile(body?.mobile),password=String(body?.password||'');if(name.length<2||name.length>120)return json({error:'Please enter a valid name.'},400);if(!validMobile(mobile))return json({error:'Please enter a valid Mobile Number.'},400);if(!validPassword(password))return json({error:'Password must be at least 8 characters.'},400)
   const{data:duplicate,error:duplicateError}=await admin.from('profiles').select('id,role,status,canteen_id').eq('mobile_number_normalized',mobile).eq('status','active').maybeSingle();if(duplicateError)return json({error:duplicateError.message},500);if(duplicate)return json({error:duplicate.canteen_id===canteenId?activeDuplicateMessage(duplicate):'This mobile number is already registered to an active account in another Canteen.'},409)
   const{data:deletedMembers,error:deletedError}=await admin.from('profiles').select('id').eq('mobile_number_normalized',mobile).eq('role','employee').eq('status','deleted');if(deletedError)return json({error:'Unable to validate the mobile number right now. Please try again.'},500)
   for(const deleted of deletedMembers||[]){const{error:deleteAuthError}=await admin.auth.admin.deleteUser(deleted.id);if(deleteAuthError&&!/not found|user.*does not exist/i.test(deleteAuthError.message||''))return json({error:'Unable to create Staff Admin account. Please try again.'},400)}
   const email=internalEmail(mobile);const{data:userList,error:listError}=await admin.auth.admin.listUsers({page:1,perPage:1000});if(listError)return json({error:'Unable to validate the mobile number right now. Please try again.'},500);const orphanUser=userList.users.find(u=>u.email===email);if(orphanUser){const{data:linked}=await admin.from('profiles').select('id,status,role').eq('id',orphanUser.id).maybeSingle();if(!linked){const{error:deleteOrphanError}=await admin.auth.admin.deleteUser(orphanUser.id);if(deleteOrphanError)return json({error:'Unable to create Staff Admin account. Please try again.'},400)}}
   let authData:any,authError:any;({data:authData,error:authError}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:name,account_type:'staff_admin'}}));if(authError||!authData.user){if(/already|exists|duplicate/i.test(authError?.message||'')){const{data:current}=await admin.from('profiles').select('id,role,status,canteen_id').eq('mobile_number_normalized',mobile).eq('status','active').maybeSingle();if(current)return json({error:current.canteen_id===canteenId?activeDuplicateMessage(current):'This mobile number is already registered to an active account in another Canteen.'},409);return json({error:'This mobile number is already registered and cannot be used for a new Admin.'},409)}return json({error:authError?.message||'Could not create Staff Admin authentication.'},400)}
   const authId=authData.user.id,employeeCode=`STAFFADMIN-${authId.replaceAll('-','')}`;const{error:profileError}=await admin.from('profiles').insert({id:authId,employee_code:employeeCode,sr_number:null,full_name:name,mobile_number:mobile,role:'admin',admin_role:'staff_admin',status:'active',is_first_login:false,canteen_id:canteenId,onboarding_completed:true});if(profileError){await admin.auth.admin.deleteUser(authId);if(profileError.code==='23505'){const{data:current}=await admin.from('profiles').select('id,role,status,canteen_id').eq('mobile_number_normalized',mobile).eq('status','active').maybeSingle();return json({error:current&&current.canteen_id===canteenId?activeDuplicateMessage(current):'This mobile number is already registered to an active account.'},409)}return json({error:profileError.message},500)}
   try{await admin.from('admin_permissions').insert({admin_id:authId,canteen_id:canteenId,permission:'dashboard',enabled:true,created_by:caller.id});await audit(authId,'create_admin',{role:'staff_admin',mobile})}catch(error){await admin.from('profiles').delete().eq('id',authId).eq('canteen_id',canteenId);await admin.auth.admin.deleteUser(authId);return json({error:error instanceof Error?error.message:'Could not finalize Admin account.'},500)}
   return json({ok:true,staff:{id:authId,full_name:name,mobile_number:mobile,status:'active',canteen_id:canteenId,admin_role:'staff_admin',permissions:['dashboard']}},201)
 }
 const staffId=String(body?.staff_id||'');if(!staffId)return json({error:'Admin account is required.'},400);const{data:staff,error:staffError}=await admin.from('profiles').select('id,full_name,mobile_number,status,canteen_id,role,admin_role').eq('id',staffId).maybeSingle();if(staffError)return json({error:staffError.message},500);if(!staff||staff.role!=='admin'||!['staff_admin','master_admin'].includes(staff.admin_role)||staff.canteen_id!==canteenId)return json({error:'Admin account not found in your Canteen.'},404)
 if(action==='reset_password'){const password=String(body?.password||'');if(!validPassword(password))return json({error:'Password must be at least 8 characters.'},400);const{error}=await admin.auth.admin.updateUserById(staff.id,{password});if(error)return json({error:safeAuthError(error,'Could not update the Admin password.')},400);try{await audit(staff.id,'reset_admin_password')}catch(error){return json({error:error instanceof Error?error.message:'Password changed, but audit logging failed. Please verify the Admin account before retrying.'},500)}return json({ok:true})}
 if(action==='update'){const name=String(body?.name??staff.full_name??'').trim(),mobile=normalizeMobile(body?.mobile??staff.mobile_number??'');if(name.length<2||name.length>120)return json({error:'Please enter a valid name.'},400);if(!validMobile(mobile))return json({error:'Please enter a valid Mobile Number.'},400);const oldMobile=normalizeMobile(staff.mobile_number||'');if(mobile!==oldMobile){const{data:duplicate,error:duplicateError}=await admin.from('profiles').select('id,role,status,canteen_id').eq('mobile_number_normalized',mobile).eq('status','active').neq('id',staff.id).maybeSingle();if(duplicateError)return json({error:duplicateError.message},500);if(duplicate)return json({error:duplicate.canteen_id===canteenId?activeDuplicateMessage(duplicate):'This mobile number is already registered to an active account in another Canteen.'},409);const{error:authError}=await admin.auth.admin.updateUserById(staff.id,{email:internalEmail(mobile),user_metadata:{full_name:name,account_type:staff.admin_role}});if(authError)return json({error:safeAuthError(authError,'Could not update the Admin login identity.')},400);const{error:profileError}=await admin.from('profiles').update({full_name:name,mobile_number:mobile}).eq('id',staff.id).eq('canteen_id',canteenId).eq('role','admin').in('admin_role',['staff_admin','master_admin']);if(profileError){await admin.auth.admin.updateUserById(staff.id,{email:internalEmail(oldMobile),user_metadata:{full_name:staff.full_name,account_type:staff.admin_role}});return json({error:profileError.message},500)}}else{const{error}=await admin.from('profiles').update({full_name:name}).eq('id',staff.id).eq('canteen_id',canteenId).eq('role','admin').in('admin_role',['staff_admin','master_admin']);if(error)return json({error:error.message},500);const{error:authError}=await admin.auth.admin.updateUserById(staff.id,{user_metadata:{full_name:name,account_type:staff.admin_role}});if(authError)return json({error:safeAuthError(authError)},400)}try{await audit(staff.id,'update_admin',{mobile_changed:mobile!==oldMobile})}catch(error){return json({error:error instanceof Error?error.message:'Admin details saved, but audit logging failed. Please verify the account before retrying.'},500)}return json({ok:true})}
 if(action==='set_role'){const target=String(body?.admin_role||'');if(!['staff_admin','master_admin'].includes(target))return json({error:'Invalid Admin Role.'},400);if(target===staff.admin_role)return json({ok:true});const{error}=await admin.from('profiles').update({admin_role:target}).eq('id',staff.id).eq('canteen_id',canteenId).eq('role','admin').in('admin_role',['staff_admin','master_admin']);if(error)return json({error:error.message},500);const{error:authError}=await admin.auth.admin.updateUserById(staff.id,{user_metadata:{account_type:target}});if(authError)return json({error:safeAuthError(authError,'Admin role was saved, but authentication metadata could not be updated.')},400);await audit(staff.id,target==='master_admin'?'promote_staff_to_master':'demote_master_to_staff',{from_role:staff.admin_role,to_role:target});return json({ok:true,admin_role:target})}
 if(action==='set_permissions'){const raw=Array.isArray(body?.permissions)?body.permissions.map((x:any)=>String(x)):[];const permissions=[...new Set(raw.filter((p:string)=>BUSINESS_PERMISSIONS.includes(p)))];const{error:deleteError}=await admin.from('admin_permissions').delete().eq('admin_id',staff.id).eq('canteen_id',canteenId);if(deleteError)return json({error:deleteError.message},500);if(permissions.length){const{error}=await admin.from('admin_permissions').insert(permissions.map(permission=>({admin_id:staff.id,canteen_id:canteenId,permission,enabled:true,created_by:caller.id})));if(error)return json({error:error.message},500)}await audit(staff.id,'update_admin_permissions',{permissions});return json({ok:true,permissions})}
 if(action==='delete_admin'){
   try{
     await audit(staff.id,'delete_admin',{role:staff.admin_role,mobile:staff.mobile_number||null});
     const{error:permError}=await admin.from('admin_permissions').delete().eq('admin_id',staff.id).eq('canteen_id',canteenId);if(permError)return json({error:permError.message},500);
     const{error:banError}=await admin.auth.admin.updateUserById(staff.id,{ban_duration:'876000h'});if(banError)return json({error:safeAuthError(banError,'Could not disable the Admin login before deletion.')},400);
     const{error:authDeleteError}=await admin.auth.admin.deleteUser(staff.id);if(authDeleteError)return json({error:safeAuthError(authDeleteError,'Could not permanently remove the Admin authentication.')},400);
     const{error:profileDeleteError}=await admin.from('profiles').delete().eq('id',staff.id).eq('canteen_id',canteenId).eq('role','admin').in('admin_role',['staff_admin','master_admin']);if(profileDeleteError)return json({error:profileDeleteError.message},500);
     return json({ok:true,deleted_admin_id:staff.id})
   }catch(error){return json({error:error instanceof Error?error.message:'Could not delete Admin account.'},500)}
 }
 if(action==='deactivate'||action==='activate'){const status=action==='activate'?'active':'blocked',ban_duration=action==='activate'?'none':'876000h';const{error:profileError}=await admin.from('profiles').update({status}).eq('id',staff.id).eq('canteen_id',canteenId).eq('role','admin').in('admin_role',['staff_admin','master_admin']);if(profileError)return json({error:profileError.message},500);const{error:authError}=await admin.auth.admin.updateUserById(staff.id,{ban_duration});if(authError){await admin.from('profiles').update({status:action==='activate'?'blocked':'active'}).eq('id',staff.id);return json({error:safeAuthError(authError,'Could not update Admin status.')},500)}await audit(staff.id,action==='activate'?'activate_admin':'deactivate_admin');return json({ok:true})}
 return json({error:'Unsupported action.'},400)
})
