import type { Order } from '../types';
import { calculateEmployeeFoodAmountFromEntries } from './employeeFoodContribution';

export interface FinancialAdjustmentLike { amount:number; contribution_eligible?:boolean; employee_food_amount?:number|null; company_food_amount?:number|null; }
export interface OrderFinancialPresentation { grossMemberFood:number; grossGuestFood:number; companyContribution:number; memberPayable:number; }
export interface DailyFinancialPresentation extends OrderFinancialPresentation { adminAddedAmount:number; totalPayable:number; }
const money=(value:unknown)=>Math.round((Number(value)||0)*100)/100;
export const grossMemberFood=(order:Order)=>Object.keys(order.items||{}).reduce((sum,code)=>sum+money(order.itemPrices?.[code])*Math.max(1,Number(order.itemQuantities?.[code]||1)),0);
export const grossGuestFood=(order:Order)=>Object.keys(order.guestItems||{}).reduce((sum,code)=>sum+money(order.guestItemPrices?.[code])*Math.max(1,Number(order.guestItemQuantities?.[code]||1)),0);
export const orderFinancialPresentation=(order:Order):OrderFinancialPresentation=>{const gross=grossMemberFood(order);const guest=grossGuestFood(order);const company=money(order.companyFoodAmount);const storedEmployee=order.employeeFoodAmount==null?null:money(order.employeeFoodAmount);if(storedEmployee!=null)return{grossMemberFood:gross,grossGuestFood:guest,companyContribution:company,memberPayable:storedEmployee};if(order.employeeContributionMode==='fixed_amount')return{grossMemberFood:gross,grossGuestFood:guest,companyContribution:Math.min(gross,company),memberPayable:Math.max(0,money(gross-company))};const grossAmounts=Object.keys(order.items||{}).map(code=>money(order.itemPrices?.[code])*Math.max(1,Number(order.itemQuantities?.[code]||1)));return{grossMemberFood:gross,grossGuestFood:guest,companyContribution:company,memberPayable:money(calculateEmployeeFoodAmountFromEntries(grossAmounts,order.employeeContributionPercentage??100))};};
export const adjustmentFinancialPresentation=(adjustment:FinancialAdjustmentLike)=>({adminAddedAmount:adjustment.contribution_eligible?money(adjustment.employee_food_amount??adjustment.amount):money(adjustment.amount),companyContribution:adjustment.contribution_eligible?money(adjustment.company_food_amount):0});
export const dailyFinancialPresentation=(orders:Order[],adjustments:FinancialAdjustmentLike[]=[]):DailyFinancialPresentation=>{const activeOrders=orders.filter(order=>order.status!=='cancelled');const orderTotals=activeOrders.reduce((sum,order)=>{const value=orderFinancialPresentation(order);sum.grossMemberFood+=value.grossMemberFood;sum.grossGuestFood+=value.grossGuestFood;sum.companyContribution+=value.companyContribution;sum.memberPayable+=value.memberPayable;return sum;},{grossMemberFood:0,grossGuestFood:0,companyContribution:0,memberPayable:0});const adjustmentTotals=adjustments.reduce((sum,adjustment)=>{const value=adjustmentFinancialPresentation(adjustment);sum.adminAddedAmount+=value.adminAddedAmount;sum.companyContribution+=value.companyContribution;return sum;},{adminAddedAmount:0,companyContribution:0});return{grossMemberFood:money(orderTotals.grossMemberFood),grossGuestFood:money(orderTotals.grossGuestFood),adminAddedAmount:money(adjustmentTotals.adminAddedAmount),companyContribution:money(orderTotals.companyContribution+adjustmentTotals.companyContribution),memberPayable:money(orderTotals.memberPayable),totalPayable:money(orderTotals.memberPayable+orderTotals.grossGuestFood+adjustmentTotals.adminAddedAmount)};};