import React,{useEffect,useMemo,useState}from'react';
import { useAuth } from '../../context/AuthContext';
import { BundleAssignment,BundleCategory,BundleMenuItem,BundleMember,WeeklyBundleReadiness,createBundleAssignment,deleteBundleAssignment,loadBundleAssignments,loadBundleCategories,loadBundleMenuItems,loadBundleMembers,loadWeeklyBundleReadiness,updateBundleAssignment } from '../../services/bundles';
type DraftItem={menu_item_code:string;quantity:number};
const pad=(n:number)=>String(n).padStart(2,'0'); const dateString=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const monthBounds=(value:string)=>{const[y,m]=value.split('-').map(Number);return{start:`${y}-${pad(m)}-01`,end:dateString(new Date(y,m,0))}};
const weekBounds=(value:string)=>{const d=new Date(`${value}T00:00:00`),day=d.getDay(),diff=day===0?-6:1-day,start=new Date(d);start.setDate(d.getDate()+diff);const end=new Date(start);end.setDate(start.getDate()+6);return{start:dateString(start),end:dateString(end)}};
const BundleManagement:React.FC=()=>{const{hasPermission}=useAuth();const[assignments,setAssignments]=useState<BundleAssignment[]>([]),[members,setMembers]=useState<BundleMember[]>([]),[categories,setCategories]=useState<BundleCategory[]>([]),[menuItems,setMenuItems]=useState<BundleMenuItem[]>([]),[weekly,setWeekly]=useState<WeeklyBundleReadiness[]>([]);const[editing,setEditing]=useState<BundleAssignment|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState('');const[memberId,setMemberId]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[type,setType]=useState<'monthly'|'weekly'>('monthly'),[categoryId,setCategoryId]=useState(''),[items,setItems]=useState<DraftItem[]>([{menu_item_code:'',quantity:1}]),[price,setPrice]=useState('');const[draftMonth,setDraftMonth]=useState(()=>{const d=new Date();return`${d.getFullYear()}-${pad(d.getMonth()+1)}`});const[week,setWeek]=useState(()=>dateString(new Date()));
 const reset=()=>{setEditing(null);setMemberId('');setName('');setDescription('');setType('monthly');setCategoryId('');setItems([{menu_item_code:'',quantity:1}]);setPrice('')};
 const load=async()=>{setLoading(true);setError('');try{const[a,m,c,mi]=await Promise.all([loadBundleAssignments(),loadBundleMembers(),loadBundleCategories(),loadBundleMenuItems()]);setAssignments(a);setMembers(m);setCategories(c);setMenuItems(mi);const b=weekBounds(week);setWeekly(await loadWeeklyBundleReadiness(b.start,b.end))}catch(e:any){setError(e?.message||'Could not load Bundles.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);const filteredItems=useMemo(()=>categoryId?menuItems.filter(i=>i.category_id===categoryId):menuItems,[menuItems,categoryId]);
 const openEdit=(a:BundleAssignment)=>{setEditing(a);setMemberId(a.member_id);setName(a.bundle_name_snapshot);setDescription(a.bundle_description_snapshot||'');setType(a.bundle_type);setCategoryId(a.category_id||'');setItems((a.items_snapshot||[]).map(x=>({menu_item_code:x.menu_item_code,quantity:Math.max(1,Number(x.quantity||1))})));setPrice(String(a.price_snapshot));if(a.bundle_type==='monthly')setDraftMonth(a.period_start.slice(0,7));else setWeek(a.period_start);window.scrollTo({top:0,behavior:'smooth'})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!hasPermission('bundles'))return;setError('');setMessage('');const selected=items.filter(x=>x.menu_item_code&&x.quantity>0);if(!memberId||!name.trim()||!selected.length||!Number.isFinite(Number(price))||Number(price)<0){setError('Member, bundle name, menu item, quantity and price are required.');return}const b=type==='monthly'?monthBounds(draftMonth):weekBounds(week);setBusy(true);try{if(editing){await updateBundleAssignment({assignment_id:editing.id,name:name.trim(),description:description.trim(),bundle_type:type,category_id:categoryId||null,items:selected,price:Number(price),period_start:b.start,period_end:b.end,status:editing.status});setMessage('Bundle updated successfully.')}else{await createBundleAssignment({member_id:memberId,name:name.trim(),description:description.trim(),bundle_type:type,category_id:categoryId||null,items:selected,price:Number(price),period_start:b.start,period_end:b.end});setMessage('Bundle created successfully. The Member received one notification.')}reset();await load()}catch(e:any){setError(e?.message||'Bundle save failed.')}finally{setBusy(false)}};
 const remove=async(a:BundleAssignment)=>{if(!window.confirm(`Delete this bundle?\n\nMember: ${a.member_name_snapshot||'Deleted Member'}\nBundle: ${a.bundle_name_snapshot}\nPeriod: ${a.billing_period}\nAmount: ₹${Number(a.price_snapshot).toFixed(2)}\n\nFinalized billing will never be deleted.`))return;setBusy(true);setError('');setMessage('');try{await deleteBundleAssignment(a.id,'Deleted by admin');setMessage('Bundle deleted safely. Historical finalized records remain unchanged.');await load()}catch(e:any){setError(e?.message||'Bundle deletion failed.')}finally{setBusy(false)}};
 if(!hasPermission('bundles'))return <div className="rounded-lg border border-red-200 bg-red-50 p-5 text-center font-semibold text-red-700">403 — Bundle permission required.</div>;
 return <div className="space-y-6"><div><h3 className="text-xl font-bold text-gray-800 sm:text-2xl">Bundles</h3><p className="mt-1 text-sm text-gray-500">Recurring Member entitlements managed separately from the normal daily Menu.</p></div>{message&&<div className="rounded-lg bg-green-50 p-3 text-sm font-semibold text-green-700">{message}</div>}{error&&<div className="rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
 <form onSubmit={save} className="rounded-xl border bg-gray-50 p-4 sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><h4 className="text-lg font-bold text-gray-800">{editing?'Edit Bundle':'Create Bundle'}</h4><p className="text-xs text-gray-500">Monthly is the default. Finalized billing periods are locked.</p></div>{editing&&<button type="button" onClick={reset} className="rounded-lg border bg-white px-3 py-2 text-sm font-semibold">Cancel Edit</button>}</div><div className="grid gap-3 sm:grid-cols-2">
 <label className="text-sm font-semibold text-gray-700">Member<select required value={memberId} onChange={e=>setMemberId(e.target.value)} disabled={Boolean(editing)||busy} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3 font-normal"><option value="">Select active Member</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}{m.mobile_number?` — ${m.mobile_number}`:''}</option>)}</select></label>
 <label className="text-sm font-semibold text-gray-700">Bundle Name<input required value={name} onChange={e=>setName(e.target.value)} disabled={busy} placeholder="Monthly Tea Bundle" className="mt-1 min-h-11 w-full rounded-lg border px-3 font-normal"/></label>
 <label className="text-sm font-semibold text-gray-700 sm:col-span-2">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} disabled={busy} rows={2} placeholder="Includes one tea per applicable day…" className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label>
 <label className="text-sm font-semibold text-gray-700">Bundle Type<select value={type} onChange={e=>setType(e.target.value as 'monthly'|'weekly')} disabled={busy} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3 font-normal"><option value="monthly">MONTHLY</option><option value="weekly">WEEKLY</option></select></label>
 <label className="text-sm font-semibold text-gray-700">Menu Category<select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setItems([{menu_item_code:'',quantity:1}])}} disabled={busy} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3 font-normal"><option value="">All / General</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <div className="sm:col-span-2"><div className="mb-2 flex items-center justify-between"><label className="text-sm font-semibold text-gray-700">Menu Item(s) &amp; Quantity</label><button type="button" onClick={()=>setItems(p=>[...p,{menu_item_code:'',quantity:1}])} className="rounded-lg border bg-white px-3 py-2 text-xs font-semibold">+ Add Item</button></div><div className="space-y-2">{items.map((item,index)=><div key={index} className="grid grid-cols-[1fr_90px_42px] gap-2"><select required value={item.menu_item_code} onChange={e=>setItems(p=>p.map((x,i)=>i===index?{...x,menu_item_code:e.target.value}:x))} disabled={busy} className="min-h-11 rounded-lg border bg-white px-3 text-sm"><option value="">Select menu item</option>{filteredItems.map(mi=><option key={mi.item_code} value={mi.item_code}>{mi.item_name} — ₹{Number(mi.unit_price).toFixed(2)}</option>)}</select><input required type="number" min="1" step="1" value={item.quantity} onChange={e=>setItems(p=>p.map((x,i)=>i===index?{...x,quantity:Math.max(1,Number(e.target.value))}:x))} disabled={busy} className="min-h-11 rounded-lg border px-3 text-center"/><button type="button" disabled={items.length===1||busy} onClick={()=>setItems(p=>p.filter((_,i)=>i!==index))} className="rounded-lg border bg-white text-red-600">×</button></div>)}</div></div>
 <label className="text-sm font-semibold text-gray-700">{type==='monthly'?'Monthly':'Weekly'} Bundle Price<div className="mt-1 flex"><span className="flex min-h-11 items-center rounded-l-lg border border-r-0 bg-white px-3 text-gray-500">₹</span><input required type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} disabled={busy} className="min-h-11 w-full rounded-r-lg border px-3 font-normal"/></div></label>
 {type==='monthly'?<label className="text-sm font-semibold text-gray-700">Month<select value={draftMonth} onChange={e=>setDraftMonth(e.target.value)} disabled={busy} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3 font-normal">{Array.from({length:15},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-2+i);const v=`${d.getFullYear()}-${pad(d.getMonth()+1)}`;return <option key={v} value={v}>{d.toLocaleString('en-IN',{month:'long',year:'numeric'})}</option>})}</select></label>:<label className="text-sm font-semibold text-gray-700">Week Starting<select value={week} onChange={e=>setWeek(e.target.value)} disabled={busy} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3 font-normal">{Array.from({length:12},(_,i)=>{const d=new Date();d.setDate(d.getDate()-d.getDay()+1+(i-4)*7);const v=dateString(d);return <option key={v} value={v}>{v} → {weekBounds(v).end}</option>})}</select></label>}
 </div><button type="submit" disabled={busy} className="mt-4 min-h-12 w-full rounded-lg bg-primary-600 px-4 font-semibold text-white disabled:opacity-50">{busy?(editing?'Saving…':'Creating…'):(editing?'Save Bundle':'Create Bundle')}</button></form>
 <section><div className="mb-3 flex items-center justify-between"><div><h4 className="text-lg font-bold text-gray-800">Existing Bundles</h4><p className="text-xs text-gray-500">Assignment history is retained; finalized billing cannot be rewritten.</p></div><button type="button" onClick={()=>void load()} className="rounded-lg border px-3 py-2 text-sm font-semibold">Refresh</button></div>{loading?<p className="rounded-lg bg-gray-50 p-4 text-sm text-gray-500">Loading Bundles…</p>:!assignments.length?<p className="rounded-lg border bg-gray-50 p-4 text-sm text-gray-500">No Bundles created yet.</p>:<div className="space-y-3">{assignments.map(a=><div key={a.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-bold text-gray-800">{a.bundle_name_snapshot}</div><div className="text-sm text-gray-600">{a.member_name_snapshot?`${a.member_name_snapshot}${a.member_mobile_snapshot?` · ${a.member_mobile_snapshot}`:''}`:'Deleted Member — historical identity'}</div><div className="mt-1 text-xs text-gray-500">{a.bundle_type.toUpperCase()} · {a.billing_period} · {a.period_start} → {a.period_end}</div></div><div className="text-right"><div className="text-lg font-bold">₹{Number(a.price_snapshot).toFixed(2)}</div><div className={`text-xs font-semibold ${a.status==='active'?'text-green-700':'text-gray-500'}`}>{a.status.toUpperCase()}</div></div></div><div className="mt-3 rounded-lg bg-gray-50 p-3 text-sm"><div className="font-semibold">Bundle Count: {a.items_snapshot.reduce((n,x)=>n+Number(x.quantity||0),0)}</div>{a.bundle_description_snapshot&&<div className="mt-1 text-gray-600">{a.bundle_description_snapshot}</div>}<div className="mt-2 space-y-1">{a.items_snapshot.map((x,i)=><div key={i} className="flex justify-between"><span>{x.item_name} × {x.quantity}</span><span>₹{(Number(x.unit_price||0)*Number(x.quantity||0)).toFixed(2)}</span></div>)}</div></div><div className="mt-3 flex justify-end gap-2"><button type="button" disabled={busy||a.status!=='active'} onClick={()=>openEdit(a)} className="rounded-lg border px-4 py-2 text-sm font-semibold disabled:opacity-40">Edit</button><button type="button" disabled={busy||a.status!=='active'} onClick={()=>void remove(a)} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Delete</button></div></div>)}</div>}</section>
 <section className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="font-bold text-gray-800">Weekly Billing Readiness</h4><p className="text-xs text-gray-500">Weekly Bundles remain separate from daily orders and daily revenue.</p></div><button type="button" onClick={()=>{const b=weekBounds(week);void loadWeeklyBundleReadiness(b.start,b.end).then(setWeekly)}} className="rounded-lg border px-3 py-2 text-sm font-semibold">Refresh</button></div>{!weekly.length?<p className="mt-3 text-sm text-gray-500">No active weekly Bundles for {weekBounds(week).start} → {weekBounds(week).end}.</p>:<div className="mt-3 space-y-2">{weekly.map(w=><div key={w.member_id} className="flex justify-between rounded-lg bg-gray-50 p-3 text-sm"><span>{w.member_name} · {w.bundle_count} Bundle(s)</span><b>₹{Number(w.bundle_total).toFixed(2)}</b></div>)}</div>}</section>
 </div>};export default BundleManagement;
