import React,{useEffect,useState}from'react';
import{useAuth}from'../../context/AuthContext';
import{loadOwnSubscription,submitSubscriptionPayment,SubscriptionPlan,CanteenSubscription,SubscriptionPayment}from'../../services/subscriptionPlatform';

const money=(n:number,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:2}).format(n||0);
const date=(v:string|null)=>v?new Date(v).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—';
const statusLabel=(s:string)=>s.replace('_',' ').toUpperCase();
const ContactUs:React.FC=()=>{const{user}=useAuth();const[data,setData]=useState<{subscription:CanteenSubscription|null;payments:SubscriptionPayment[];plans:SubscriptionPlan[]}|null>(null);const[error,setError]=useState('');const[message,setMessage]=useState('');const[amount,setAmount]=useState('');const[reference,setReference]=useState('');const[paymentDate,setPaymentDate]=useState(new Date().toISOString().slice(0,10));const[saving,setSaving]=useState(false);
const load=async()=>{if(!user?.canteenId)return;try{setError('');setData(await loadOwnSubscription(user.canteenId))}catch(e:any){setError(e?.message||'Could not load Billing & Subscription information.')}};useEffect(()=>{void load()},[user?.canteenId]);
useEffect(()=>{if(data?.subscription)setAmount(String(data.subscription.amount||''))},[data?.subscription?.id,data?.subscription?.amount]);
const subscription=data?.subscription;const plan=subscription?data?.plans.find(p=>p.id===subscription.plan_id):null;const canSubmit=Boolean(subscription&&['payment_pending','expired'].includes(subscription.status));
const submit=async()=>{if(!subscription||!user?.canteenId||saving)return;const numeric=Number(amount);if(!Number.isFinite(numeric)||numeric<=0){setError('Enter a valid payment amount.');return}if(!reference.trim()){setError('Enter the payment reference / transaction ID.');return}if(!paymentDate){setError('Select the payment date.');return}setSaving(true);setError('');setMessage('');try{await submitSubscriptionPayment(subscription.id,numeric,reference.trim(),paymentDate);setMessage('Payment submitted successfully. It is pending Super Admin verification.');setReference('');await load()}catch(e:any){setError(e?.message||'Could not submit payment.')}finally{setSaving(false)}};
return <div className="w-full min-w-0 space-y-4"><div className="mb-5"><h3 className="text-xl font-bold text-gray-800 sm:text-2xl">Billing & Subscription</h3><p className="mt-1 text-sm text-gray-500">Subscription, payment and GoCanteen support information for this Canteen only.</p></div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}{message&&<div className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm font-semibold text-green-700">{message}</div>}{!data&&!error&&<div className="rounded-xl border bg-white p-5 text-sm text-gray-500">Loading subscription information…</div>}{data&&<>{!subscription?<div className="rounded-xl border bg-white p-5"><p className="font-bold">No GoCanteen subscription has been assigned yet.</p><p className="mt-1 text-sm text-gray-500">Please contact GoCanteen support.</p></div>:<><section className="rounded-xl border bg-white p-4 shadow-sm sm:p-5"><h4 className="font-extrabold text-gray-800">Current Subscription</h4><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs font-bold text-gray-500">Current Plan</p><p className="mt-1 font-extrabold">{plan?.name||'—'}</p></div><div><p className="text-xs font-bold text-gray-500">Subscription Status</p><p className="mt-1 font-extrabold">{statusLabel(subscription.status)}</p></div><div><p className="text-xs font-bold text-gray-500">Amount</p><p className="mt-1 font-extrabold">{money(subscription.amount,subscription.currency)}</p></div><div><p className="text-xs font-bold text-gray-500">Payment Status</p><p className="mt-1 font-extrabold">{statusLabel(subscription.payment_status)}</p></div><div><p className="text-xs font-bold text-gray-500">Trial Start</p><p className="mt-1">{date(subscription.trial_start)}</p></div><div><p className="text-xs font-bold text-gray-500">Trial End</p><p className="mt-1">{date(subscription.trial_end)}</p></div><div><p className="text-xs font-bold text-gray-500">Subscription Start</p><p className="mt-1">{date(subscription.subscription_start)}</p></div><div><p className="text-xs font-bold text-gray-500">Subscription End</p><p className="mt-1">{date(subscription.subscription_end)}</p></div></div></section>
<section className="rounded-xl border bg-white p-4 shadow-sm sm:p-5"><h4 className="font-extrabold text-gray-800">Payment</h4>{canSubmit?<div className="mt-4 space-y-3"><p className="text-sm text-gray-600">Payment is required for this subscription. Submit your payment details for Super Admin verification.</p><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold text-gray-700">Amount<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold text-gray-700">Payment Date<input type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold text-gray-700">Payment Reference / Transaction ID<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Enter reference" className="mt-1 w-full rounded-lg border px-3 py-2.5 font-normal"/></label></div><button type="button" disabled={saving} onClick={()=>void submit()} className="rounded-lg bg-primary-600 px-4 py-2.5 font-bold text-white disabled:opacity-50">{saving?'Submitting…':'Submit Payment'}</button></div>:<p className="mt-2 text-sm text-gray-600">{subscription.status==='active'?'No payment is currently required.':subscription.status==='trial'?'Your trial is currently active.':'Please contact GoCanteen support for payment instructions.'}</p>}</section>
<section className="rounded-xl border bg-white p-4 shadow-sm sm:p-5"><h4 className="font-extrabold text-gray-800">Payment History</h4><div className="mt-3 space-y-2">{data.payments.length?data.payments.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-sm"><div><p className="font-semibold">{money(p.amount,p.currency)} · {p.transaction_reference||'No reference'}</p><p className="text-xs text-gray-500">Payment date: {date(p.payment_date)}{p.billing_period_start&&p.billing_period_end?' · Billing period: '+date(p.billing_period_start)+' – '+date(p.billing_period_end):''}</p></div><span className="font-bold">{statusLabel(p.payment_status)}</span></div>):<p className="text-sm text-gray-500">No subscription payments yet.</p>}</div></section></>}</>}</div>};
export default ContactUs;
