import React,{useEffect,useMemo,useState}from'react';
import{useData}from'../../context/DataContext';
import{loadEmployeeFoodContributionSettingsForAdmin,saveEmployeeFoodContributionSettings,EmployeeFoodContributionMode,EmployeeFoodContributionSettings}from'../../services/employeeFoodContribution';
import{supabase}from'../../supabase';
import AsyncActionButton from'../common/AsyncActionButton';

const EmployeeFoodArrangementSettings:React.FC=()=>{
 const{users}=useData();
 const employees=useMemo(()=>users.filter(u=>u.role==='employee'&&u.status!=='deleted'),[users]);
 const[settings,setSettings]=useState<Record<string,EmployeeFoodContributionSettings>>({});
 const[selectedEmployeeId,setSelectedEmployeeId]=useState('');
 const[mode,setMode]=useState<EmployeeFoodContributionMode>('percentage');
 const[percentage,setPercentage]=useState('0');
 const[fixedAmount,setFixedAmount]=useState('0');
 const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[editing,setEditing]=useState(false);const[locked,setLocked]=useState(false);const[msg,setMsg]=useState('');
 const selectedSetting=selectedEmployeeId?settings[selectedEmployeeId]:undefined;
 const loadLock=async()=>{if(!supabase)return;try{const{data,error}=await supabase.rpc('employee_food_contribution_setting_locked');if(!error)setLocked(Boolean(data))}catch{setLocked(false)}};
 const applySetting=(value:EmployeeFoodContributionSettings|undefined)=>{const next=value||{employeeId:selectedEmployeeId,contributionMode:'percentage',employeeContributionPercentage:0,fixedMonthlyAmount:0};setMode(next.contributionMode);setPercentage(String(next.employeeContributionPercentage));setFixedAmount(String(next.fixedMonthlyAmount));setEditing(false)};
 useEffect(()=>{let alive=true;void Promise.all([loadEmployeeFoodContributionSettingsForAdmin(),loadLock()]).then(([rows])=>{if(!alive)return;const map:Record<string,EmployeeFoodContributionSettings>={};(rows as EmployeeFoodContributionSettings[]).forEach(row=>{map[row.employeeId]=row});setSettings(map);const first=employees[0]?.identityId||employees[0]?.id||'';setSelectedEmployeeId(first);applySetting(first?map[first]:undefined)}).catch((e:any)=>{if(alive)setMsg(e?.message||'Could not load employee food arrangement.')}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[employees]);
 useEffect(()=>{if(selectedEmployeeId)applySetting(settings[selectedEmployeeId])},[selectedEmployeeId]);
 const numericPercentage=Number(percentage);const numericFixed=Number(fixedAmount);const validPercentage=Number.isFinite(numericPercentage)&&numericPercentage>=0&&numericPercentage<=100;const validFixed=Number.isFinite(numericFixed)&&numericFixed>=0;const valid=mode==='percentage'?validPercentage:validFixed;
 const selectedEmployee=employees.find(e=>(e.identityId||e.id)===selectedEmployeeId);const save=async()=>{if(saving||locked||!selectedEmployeeId||!valid)return;setSaving(true);setMsg('');try{const next=await saveEmployeeFoodContributionSettings(selectedEmployeeId,mode,numericPercentage,numericFixed);setSettings(prev=>({...prev,[selectedEmployeeId]:{...next,employeeName:selectedEmployee?.name,employeeCode:selectedEmployee?.id}}));applySetting(next);setMsg('Employee food contribution saved successfully.');await loadLock()}catch(e:any){setMsg(e?.message||'Could not save employee food contribution.')}finally{setSaving(false)}};
 return <section className="rounded-xl border bg-white p-4"><div><h4 className="font-bold">Employee Food Arrangement</h4><p className="mt-1 text-sm text-gray-500">Configure the company food contribution separately for each employee. Fixed Amount is a monthly company-covered allowance, not an order limit.</p></div><div className="mt-4 max-w-xl space-y-4">
 <label className="block text-sm font-semibold text-gray-700">Employee<select disabled={loading||saving||editing} value={selectedEmployeeId} onChange={e=>{setSelectedEmployeeId(e.target.value);setMsg('')}} className="mt-1 block w-full rounded-lg border px-3 py-2.5 disabled:bg-gray-50"><option value="">Select employee</option>{employees.map(e=><option key={e.identityId||e.id} value={e.identityId||e.id}>{e.name}{e.id?` — ${e.id}`:''}</option>)}</select></label>
 <div><div className="text-sm font-semibold text-gray-700">Contribution Mode</div><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" disabled={loading||saving||locked||!editing} onClick={()=>{setMode('percentage');setMsg('')}} className={`min-h-11 rounded-lg border px-3 py-2 text-sm font-semibold ${mode==='percentage'?'border-primary-600 bg-primary-50 text-primary-700':'text-gray-600'}`}>Percentage</button><button type="button" disabled={loading||saving||locked||!editing} onClick={()=>{setMode('fixed_amount');setMsg('')}} className={`min-h-11 rounded-lg border px-3 py-2 text-sm font-semibold ${mode==='fixed_amount'?'border-primary-600 bg-primary-50 text-primary-700':'text-gray-600'}`}>Fixed Amount</button></div></div>
 {mode==='percentage'?<label className="block text-sm font-semibold text-gray-700">Employee Food Contribution<input disabled={loading||saving||locked||!editing} type="number" min="0" max="100" step="1" inputMode="numeric" value={percentage} onChange={e=>{setPercentage(e.target.value);setMsg('')}} className="mt-1 block w-full rounded-lg border px-3 py-2.5 disabled:bg-gray-50"/><span className="mt-1 block text-xs text-gray-500">Range: 0–100%. 0% means the employee pays the full eligible gross amount.</span></label>:<label className="block text-sm font-semibold text-gray-700">Monthly Company-Covered Allowance<input disabled={loading||saving||locked||!editing} type="number" min="0" step="0.01" inputMode="decimal" value={fixedAmount} onChange={e=>{setFixedAmount(e.target.value);setMsg('')}} className="mt-1 block w-full rounded-lg border px-3 py-2.5 disabled:bg-gray-50"/><span className="mt-1 block text-xs text-gray-500">₹{Number.isFinite(numericFixed)?numericFixed.toFixed(2):'0.00'} per calendar month. This does not limit order size. Once the allowance is used, the employee pays the remaining eligible food amount.</span></label>}
 {mode==='percentage'&&validPercentage&&<div className="rounded-lg bg-primary-50 p-3 text-sm"><div className="font-semibold text-primary-800">Employee Contribution: {numericPercentage}%</div><div className="mt-1 font-semibold text-primary-800">Company Contribution: {100-numericPercentage}%</div></div>}
 {mode==='percentage'&&!validPercentage&&<p className="text-sm text-red-600">Enter a percentage from 0% to 100%.</p>}{mode==='fixed_amount'&&!validFixed&&<p className="text-sm text-red-600">Enter a monthly allowance of ₹0 or more.</p>}
 {locked&&<p className="rounded-lg bg-amber-50 p-3 text-sm font-semibold text-amber-800">Locked — Order Time is currently open. The current employee contribution setting cannot be changed during the active order cycle.</p>}
 {!loading&&selectedEmployee&&<div className="rounded-lg border bg-gray-50 p-3 text-sm"><div className="font-semibold">Current setting for {selectedEmployee.name}</div><div className="mt-1">{selectedSetting?.contributionMode==='fixed_amount'?`Fixed Amount — ₹${Number(selectedSetting.fixedMonthlyAmount||0).toFixed(2)} / month`:`Percentage — ${Number(selectedSetting?.employeeContributionPercentage||0)}%`}</div></div>}
 <div className="flex flex-col gap-2 sm:flex-row">{!editing?<button type="button" disabled={loading||saving||locked||!selectedEmployeeId} onClick={()=>{setEditing(true);setMsg('')}} className="min-h-11 rounded-lg border px-5 font-semibold text-gray-700">Edit</button>:<><AsyncActionButton type="button" loading={saving} loadingLabel="Saving…" disabled={loading||saving||locked||!selectedEmployeeId||!valid} onClick={()=>void save()} className="min-h-11 rounded-lg bg-primary-600 px-5 font-semibold text-white">Save</AsyncActionButton><button type="button" disabled={saving} onClick={()=>{applySetting(selectedSetting);setMsg('')}} className="min-h-11 rounded-lg border px-5 font-semibold text-gray-700">Cancel</button></>}{msg&&<p className="rounded-lg bg-gray-50 p-3 text-sm text-gray-700 sm:ml-2">{msg}</p>}</div>
 </div></section>;
};export default EmployeeFoodArrangementSettings;
