import React,{useEffect,useState}from'react';
import{loadEmployeeFoodContributionPercentage,saveEmployeeFoodContributionPercentage}from'../../services/employeeFoodContribution';
import{supabase}from'../../supabase';
import AsyncActionButton from'../common/AsyncActionButton';

const EmployeeFoodArrangementSettings:React.FC=()=>{const[value,setValue]=useState('0');const[saved,setSaved]=useState(0);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[locked,setLocked]=useState(false);const[msg,setMsg]=useState('');
const loadLock=async()=>{if(!supabase)return;try{const{data,error}=await supabase.rpc('employee_food_contribution_setting_locked');if(!error)setLocked(Boolean(data))}catch{setLocked(false)}};
useEffect(()=>{let alive=true;void Promise.all([loadEmployeeFoodContributionPercentage(),loadLock()]).then(([v])=>{if(alive){setSaved(v);setValue(String(v))}}).catch((e:any)=>{if(alive)setMsg(e?.message||'Could not load employee food arrangement.')}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[]);
const numeric=Number(value);const valid=Number.isFinite(numeric)&&numeric>=0&&numeric<=100;const save=async()=>{if(saving||locked||!valid)return;setSaving(true);setMsg('');try{const next=await saveEmployeeFoodContributionPercentage(numeric);setSaved(next);setValue(String(next));setMsg('Employee food contribution saved successfully.');await loadLock()}catch(e:any){setMsg(e?.message||'Could not save employee food contribution.')}finally{setSaving(false)}};
return <section className="rounded-xl border bg-white p-4"><div><h4 className="font-bold">Employee Food Arrangement</h4><p className="mt-1 text-sm text-gray-500">Set the percentage of food value personally paid by employees. 0% keeps the existing Go Canteen behaviour.</p></div><div className="mt-4 max-w-md"><label className="text-sm font-semibold text-gray-700">Employee Food Contribution<input disabled={loading||saving||locked} type="number" min="0" max="100" step="1" inputMode="numeric" value={value} onChange={e=>{setValue(e.target.value);setMsg('')}} className="mt-1 block w-full rounded-lg border px-3 py-2.5 disabled:bg-gray-50"/><span className="mt-1 block text-xs text-gray-500">Range: 0–100%</span></label>{locked&&<p className="mt-2 rounded-lg bg-amber-50 p-3 text-sm font-semibold text-amber-800">Locked — Order Time is currently open. The current percentage remains fixed for this active order cycle.</p>}{numeric>0&&valid&&<div className="mt-3 rounded-lg bg-primary-50 p-3 text-sm"><div className="font-semibold text-primary-800">Employee Contribution: {numeric}%</div><div className="mt-1 font-semibold text-primary-800">Company Contribution: {100-numeric}%</div></div>}{!valid&&<p className="mt-2 text-sm text-red-600">Enter a percentage from 0% to 100%.</p>}<AsyncActionButton type="button" loading={saving} loadingLabel="Saving…" disabled={loading||saving||locked||!valid} onClick={()=>void save()} className="mt-4 min-h-11 rounded-lg bg-primary-600 px-5 font-semibold text-white">Save</AsyncActionButton>{msg&&<p className="mt-3 rounded-lg bg-gray-50 p-3 text-sm text-gray-700">{msg}</p>}{!loading&&<p className="mt-3 text-xs text-gray-500">Current setting: {saved}%</p>}</div></section>};export default EmployeeFoodArrangementSettings;
