import React, { useEffect, useMemo, useState } from 'react';
import { supabase, supabaseEnabled } from '../../supabase';

interface Expense { id:string; expense_date:string; amount:number; description:string; }
const iso=(d:Date)=>d.toISOString().slice(0,10);
const Expenses:React.FC=()=>{
 const [mode,setMode]=useState<'day'|'week'|'month'>('month'); const [date,setDate]=useState(iso(new Date())); const [items,setItems]=useState<Expense[]>([]); const [amount,setAmount]=useState(''); const [description,setDescription]=useState(''); const [editing,setEditing]=useState<string|null>(null);
 const load=async()=>{if(!supabaseEnabled||!supabase)return; const {data,error}=await supabase.from('expenses').select('id,expense_date,amount,description').order('expense_date',{ascending:false}); if(!error)setItems((data||[]).map((x:any)=>({...x,amount:Number(x.amount)})));}; useEffect(()=>{void load()},[]);
 const range=useMemo(()=>{const d=new Date(`${date}T00:00:00`); if(mode==='day')return [date,date]; if(mode==='month'){const start=new Date(d.getFullYear(),d.getMonth(),1),end=new Date(d.getFullYear(),d.getMonth()+1,0);return[iso(start),iso(end)]} const day=d.getDay()||7; const start=new Date(d);start.setDate(d.getDate()-day+1);const end=new Date(start);end.setDate(start.getDate()+6);return[iso(start),iso(end)]},[date,mode]);
 const visible=items.filter(x=>x.expense_date>=range[0]&&x.expense_date<=range[1]); const total=visible.reduce((s,x)=>s+x.amount,0);
 const save=async()=>{if(!supabaseEnabled||!supabase||!amount)return; const payload={expense_date:date,amount:Number(amount),description:description.trim()}; if(editing)await supabase.from('expenses').update(payload).eq('id',editing);else await supabase.from('expenses').insert(payload);setAmount('');setDescription('');setEditing(null);await load()};
 const remove=async(id:string)=>{if(!supabase||!confirm('Delete this expense?'))return;await supabase.from('expenses').delete().eq('id',id);await load()};
 return <div><h3 className="text-2xl font-bold text-gray-800">Expenses</h3><p className="mt-1 text-sm text-gray-500">Admin-only expense tracking and net revenue.</p><div className="mt-4 grid gap-2 sm:grid-cols-3"><select value={mode} onChange={e=>setMode(e.target.value as any)} className="rounded-md border p-2.5"><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option></select><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-md border p-2.5"/><div className="rounded-md bg-gray-50 p-2.5 font-semibold">Expenses: ₹{total.toFixed(2)}</div></div><div className="mt-4 rounded-lg border p-4"><div className="grid gap-2 sm:grid-cols-3"><input type="number" min="0" step="0.01" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)} className="rounded-md border p-2.5"/><input placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)} className="rounded-md border p-2.5"/><button onClick={save} className="rounded-md bg-primary-600 px-4 py-2.5 font-medium text-white">{editing?'Update':'Add'} Expense</button></div></div><div className="mt-4 space-y-2">{visible.map(x=><div key={x.id} className="flex items-center justify-between rounded-lg border p-3"><div><div className="font-semibold">₹{x.amount.toFixed(2)}</div><div className="text-sm text-gray-500">{x.expense_date} • {x.description||'—'}</div></div><div className="flex gap-2"><button onClick={()=>{setEditing(x.id);setAmount(String(x.amount));setDescription(x.description)}} className="rounded border px-3 py-1.5 text-sm">Edit</button><button onClick={()=>void remove(x.id)} className="rounded border px-3 py-1.5 text-sm text-red-600">Delete</button></div></div>)}</div></div>
}; export default Expenses;
