import React,{useEffect,useState}from'react';
import{normalizeMobileNumber,supabase}from'../../supabase';

type Staff={id:string;full_name:string;mobile_number:string;status:string;admin_role:string};
const call=async(body:Record<string,unknown>)=>{if(!supabase)throw new Error('Supabase is not enabled.');const{data,error}=await supabase.functions.invoke('manage-staff-admin',{body});if(error){try{const c=(error as any)?.context;if(c?.json){const p=await c.json();if(p?.error)throw new Error(String(p.error))}}catch(e:any){if(e?.message&&!String(e.message).includes('body'))throw e}throw error}if(data?.error)throw new Error(String(data.error));return data as any};
const StaffAdminManagement:React.FC=()=>{
 const[staff,setStaff]=useState<Staff[]>([]);const[showCreate,setShowCreate]=useState(false);const[form,setForm]=useState({name:'',mobile:'',password:''});const[edit,setEdit]=useState<Staff|null>(null);const[editForm,setEditForm]=useState({name:'',mobile:''});const[resetId,setResetId]=useState<string|null>(null);const[resetPassword,setResetPassword]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');
 const load=async()=>{try{const r=await call({action:'list'});setStaff(r.staff||[])}catch(e:any){setError(e?.message||'Could not load Staff Admins.')}};
 useEffect(()=>{void load()},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSuccess('');const mobile=normalizeMobileNumber(form.mobile);if(!form.name.trim()){setError('Name is required.');return}if(!/^[6-9][0-9]{9}$/.test(mobile)){setError('Please enter a valid Mobile Number.');return}if(form.password.length<8){setError('Password must be at least 8 characters.');return}setBusy(true);try{await call({action:'create',name:form.name.trim(),mobile,password:form.password});setForm({name:'',mobile:'',password:''});setShowCreate(false);await load();setSuccess('Staff Admin created successfully.');}catch(e:any){setError(e?.message||'Could not create Staff Admin.')}finally{setBusy(false)}};
 const saveEdit=async()=>{if(!edit)return;setError('');setSuccess('');const mobile=normalizeMobileNumber(editForm.mobile);if(!editForm.name.trim()){setError('Name is required.');return}if(!/^[6-9][0-9]{9}$/.test(mobile)){setError('Please enter a valid Mobile Number.');return}setBusy(true);try{await call({action:'update',staff_id:edit.id,name:editForm.name.trim(),mobile});setEdit(null);await load();setSuccess('Staff Admin details updated.');}catch(e:any){setError(e?.message||'Could not update Staff Admin.')}finally{setBusy(false)}};
 const reset=async()=>{if(!resetId)return;setError('');setSuccess('');if(resetPassword.length<8){setError('Password must be at least 8 characters.');return}setBusy(true);try{await call({action:'reset_password',staff_id:resetId,password:resetPassword});setResetId(null);setResetPassword('');setSuccess('Staff Admin password reset successfully.');}catch(e:any){setError(e?.message||'Could not reset password.')}finally{setBusy(false)}};
 const toggle=async(s:Staff)=>{setError('');setSuccess('');setBusy(true);try{await call({action:s.status==='active'?'deactivate':'activate',staff_id:s.id});await load();setSuccess(s.status==='active'?'Staff Admin deactivated.':'Staff Admin reactivated.');}catch(e:any){setError(e?.message||'Could not update Staff Admin status.')}finally{setBusy(false)}};
 return <div className="space-y-4"><div className="rounded-lg border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="text-lg font-bold">MANAGE STAFF / ADMIN ROLES</h4><p className="mt-1 text-sm text-gray-500">Create and manage Staff Admin accounts for this Canteen.</p></div><button type="button" onClick={()=>{setShowCreate(v=>!v);setError('');setSuccess('')}} className="rounded-md bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white">{showCreate?'Close':'＋ Create New Admin Role'}</button></div>{error&&<div className="mt-4 whitespace-pre-line rounded-md bg-red-100 p-3 text-sm text-red-700">{error}</div>}{success&&<div className="mt-4 rounded-md bg-green-100 p-3 text-sm text-green-700">{success}</div>}
 {showCreate&&<form onSubmit={create} className="mt-4 rounded-lg border bg-gray-50 p-4"><div className="mb-4 rounded-lg border border-primary-200 bg-primary-50 p-4 text-sm text-gray-700"><p className="font-bold text-primary-800">ADMIN ROLE LOGIN INFORMATION</p><p className="mt-2"><strong>User ID:</strong> Staff Admin's Mobile Number</p><p><strong>Password:</strong> The password set by the Owner/Admin during creation.</p><p className="mt-2"><strong>Staff Admin will log in using:</strong> Mobile Number + Password</p><p>Gmail is not required for Staff Admin login.</p></div><div className="grid gap-3 md:grid-cols-3"><input required placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="rounded-md border px-3 py-2.5"/><input required inputMode="tel" placeholder="Mobile Number" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} className="rounded-md border px-3 py-2.5"/><input required type="password" minLength={8} placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="rounded-md border px-3 py-2.5"/></div><button disabled={busy} className="mt-3 rounded-md bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?'Creating…':'Create New Admin Role'}</button></form>}
 </div><div className="rounded-lg border bg-white p-4"><h4 className="font-bold">MANAGE STAFF</h4>{staff.length===0?<p className="mt-3 text-sm text-gray-500">No Staff Admin accounts yet.</p>:<div className="mt-3 space-y-3">{staff.map(s=><div key={s.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{s.full_name}</p><p className="text-sm text-gray-500">Mobile: {s.mobile_number}</p><p className="text-sm text-gray-600">Role: Staff Admin · Status: <span className="capitalize">{s.status}</span></p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>{setEdit(s);setEditForm({name:s.full_name,mobile:s.mobile_number});setError('');setSuccess('')}} className="rounded-md border px-3 py-2 text-sm">Edit</button><button type="button" onClick={()=>{setResetId(s.id);setResetPassword('');setError('');setSuccess('')}} className="rounded-md bg-primary-600 px-3 py-2 text-sm text-white">Reset Password</button><button type="button" disabled={busy} onClick={()=>void toggle(s)} className={`rounded-md px-3 py-2 text-sm text-white ${s.status==='active'?'bg-red-600':'bg-green-600'}`}>{s.status==='active'?'Deactivate':'Activate'}</button></div></div>{edit?.id===s.id&&<div className="mt-3 rounded-md bg-gray-50 p-3"><div className="grid gap-2 md:grid-cols-2"><input value={editForm.name} onChange={e=>setEditForm({...editForm,name:e.target.value})} placeholder="Name" className="rounded-md border px-3 py-2.5"/><input value={editForm.mobile} onChange={e=>setEditForm({...editForm,mobile:e.target.value})} inputMode="tel" placeholder="Mobile Number" className="rounded-md border px-3 py-2.5"/></div><div className="mt-2 flex gap-2"><button type="button" disabled={busy} onClick={()=>void saveEdit()} className="rounded-md bg-primary-600 px-3 py-2 text-sm text-white">Save</button><button type="button" onClick={()=>setEdit(null)} className="rounded-md border px-3 py-2 text-sm">Cancel</button></div></div>}{resetId===s.id&&<div className="mt-3 rounded-md bg-gray-50 p-3"><input autoFocus type="password" minLength={8} placeholder="New Password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} className="w-full rounded-md border px-3 py-2.5"/><div className="mt-2 flex gap-2"><button type="button" disabled={busy} onClick={()=>void reset()} className="rounded-md bg-primary-600 px-3 py-2 text-sm text-white">Set New Password</button><button type="button" onClick={()=>setResetId(null)} className="rounded-md border px-3 py-2 text-sm">Cancel</button></div></div>}</div>)}</div>}</div></div>;
};
export default StaffAdminManagement;
