create or replace function public.super_admin_upsert_subscription_plan(p_plan_id uuid default null,p_name text default null,p_description text default null,p_pricing_model text default 'MEMBER_RANGE',p_billing_cycle text default 'monthly',p_currency text default 'INR',p_monthly_price numeric default null,p_annual_price numeric default null,p_ranges jsonb default '[]'::jsonb,p_active boolean default true,p_is_default boolean default false)
returns public.subscription_plans language plpgsql security definer set search_path=''
as $$
declare v_plan public.subscription_plans; v_range jsonb; v_min integer; v_max integer; v_monthly numeric(12,2); v_annual numeric(12,2);
begin
if not public.is_super_admin() then raise exception 'Super Admin authorization required'; end if;
if nullif(trim(coalesce(p_name,'')),'') is null then raise exception 'Plan name is required'; end if;
if p_pricing_model not in ('FIXED_AMOUNT','MEMBER_RANGE') then raise exception 'Invalid pricing model'; end if;
if p_pricing_model='FIXED_AMOUNT' then if p_monthly_price is null or p_monthly_price<0 then raise exception 'Fixed monthly amount is required'; end if; p_billing_cycle:='monthly'; p_annual_price:=p_monthly_price; p_ranges:='[]'::jsonb; else if p_billing_cycle not in ('monthly','annual') then raise exception 'MEMBER_RANGE billing cycle must be monthly or annual'; end if; if jsonb_typeof(coalesce(p_ranges,'[]'::jsonb))<>'array' or jsonb_array_length(coalesce(p_ranges,'[]'::jsonb))=0 then raise exception 'At least one member pricing range is required'; end if; end if;
if p_plan_id is null then insert into public.subscription_plans(name,description,pricing_model,min_members,max_members,monthly_price,annual_price,price,billing_period,currency,trial_days,active,is_default,billing_cycle) values(trim(p_name),nullif(trim(p_description),''),p_pricing_model,case when p_pricing_model='MEMBER_RANGE' then 0 else null end,case when p_pricing_model='MEMBER_RANGE' then 2147483647 else null end,coalesce(p_monthly_price,0),coalesce(p_annual_price,coalesce(p_monthly_price,0)),coalesce(p_monthly_price,0),'monthly',upper(trim(coalesce(p_currency,'INR'))),0,p_active,false,p_billing_cycle) returning * into v_plan; else select * into v_plan from public.subscription_plans where id=p_plan_id for update; if not found then raise exception 'Plan not found'; end if; update public.subscription_plans set name=trim(p_name),description=nullif(trim(p_description),''),pricing_model=p_pricing_model,billing_cycle=p_billing_cycle,currency=upper(trim(coalesce(p_currency,'INR'))),monthly_price=coalesce(p_monthly_price,monthly_price),annual_price=coalesce(p_annual_price,coalesce(p_monthly_price,annual_price)),price=coalesce(p_monthly_price,monthly_price),billing_period='monthly',active=p_active,updated_at=now() where id=v_plan.id returning * into v_plan; delete from public.subscription_plan_ranges where plan_id=v_plan.id; end if;
if v_plan.pricing_model='MEMBER_RANGE' then for v_range in select value from jsonb_array_elements(coalesce(p_ranges,'[]'::jsonb)) loop v_min:=coalesce((v_range->>'min_members')::integer,(v_range->>'min')::integer); v_max:=coalesce((v_range->>'max_members')::integer,(v_range->>'max')::integer); v_monthly:=coalesce((v_range->>'monthly_price')::numeric,(v_range->>'price')::numeric); v_annual:=coalesce((v_range->>'annual_price')::numeric,v_monthly); if v_min is null or v_max is null or v_monthly is null or v_annual is null or v_min<0 or v_max<v_min or v_monthly<0 or v_annual<0 then raise exception 'Invalid member pricing range'; end if; if exists(select 1 from public.subscription_plan_ranges x where x.plan_id=v_plan.id and x.min_members<=v_max and v_min<=x.max_members) then raise exception 'Member pricing ranges cannot overlap'; end if; insert into public.subscription_plan_ranges(plan_id,min_members,max_members,monthly_price,annual_price) values(v_plan.id,v_min,v_max,v_monthly,v_annual); end loop; select min(min_members),max(max_members),min(monthly_price),min(annual_price) into v_plan.min_members,v_plan.max_members,v_plan.monthly_price,v_plan.annual_price from public.subscription_plan_ranges where plan_id=v_plan.id; update public.subscription_plans set min_members=v_plan.min_members,max_members=v_plan.max_members,monthly_price=v_plan.monthly_price,annual_price=v_plan.annual_price,price=v_plan.monthly_price,updated_at=now() where id=v_plan.id returning * into v_plan; else update public.subscription_plans set min_members=null,max_members=null,annual_price=monthly_price,price=monthly_price,billing_cycle='monthly',updated_at=now() where id=v_plan.id returning * into v_plan; end if;
if p_is_default then update public.subscription_plans set is_default=false,updated_at=now() where is_default and id<>v_plan.id; update public.subscription_plans set is_default=true,updated_at=now() where id=v_plan.id returning * into v_plan; end if; return v_plan; end $$;