-- Extends existing bill_payments; never deletes payment history.
alter table public.bill_payments drop constraint if exists bill_payments_status_check;
alter table public.bill_payments add constraint bill_payments_status_check check (status in ('unpaid','pending_verification','paid','not_received','rejected'));
alter table public.bill_payments add column if not exists payment_reference text;
alter table public.bill_payments add column if not exists covered_through date;
alter table public.bill_payments add column if not exists request_sequence integer;
create unique index if not exists bill_payments_payment_reference_key on public.bill_payments(payment_reference) where payment_reference is not null;
create index if not exists bill_payments_bill_created_idx on public.bill_payments(bill_id,created_at);
update public.bill_payments p set payment_reference='GoCanteen-'||coalesce(mb.bill_year::text,'0000')||'-'||lpad(coalesce(mb.bill_month,0)::text,2,'0')||'-'||left(p.id::text,8) from public.monthly_bills mb where mb.id=p.bill_id and (p.payment_reference is null or btrim(p.payment_reference)='');
update public.bill_payments p set covered_through=coalesce(p.covered_through,mb.billing_end_date) from public.monthly_bills mb where mb.id=p.bill_id;

create or replace function public.publish_employee_bill(p_employee_id uuid,p_month integer,p_year integer,p_food_total numeric,p_admin_added_total numeric,p_guest_food_total numeric default 0,p_days_ordered integer default 0,p_billing_start_date date default null,p_billing_end_date date default null) returns public.monthly_bills language plpgsql security definer set search_path=public as $$
declare v_admin public.profiles%rowtype;v_employee public.profiles%rowtype;v_bill public.monthly_bills%rowtype;v_now timestamptz:=now();v_total numeric:=greatest(coalesce(p_food_total,0),0)+greatest(coalesce(p_admin_added_total,0),0);v_paid numeric:=0;v_pending numeric:=0;v_requestable numeric:=0;v_seq integer:=1;v_id uuid;v_ref text;
begin
select * into v_admin from public.profiles where id=auth.uid() and role='admin' and status='active' and canteen_id=public.current_canteen_id();if not found then raise exception 'Admin authorization required';end if;
select * into v_employee from public.profiles where id=p_employee_id and role='employee' and canteen_id=public.current_canteen_id();if not found then raise exception 'Employee not found in current canteen';end if;
insert into public.monthly_bills(employee_id,bill_month,bill_year,billing_start_date,billing_end_date,days_ordered,food_total,guest_food_total,admin_added_total,total,published,published_at,updated_at,canteen_id) values(p_employee_id,p_month,p_year,coalesce(p_billing_start_date,make_date(p_year,p_month,1)),coalesce(p_billing_end_date,(make_date(p_year,p_month,1)+interval '1 month - 1 day')::date),greatest(coalesce(p_days_ordered,0),0),greatest(coalesce(p_food_total,0),0),greatest(coalesce(p_guest_food_total,0),0),greatest(coalesce(p_admin_added_total,0),0),v_total,true,v_now,v_now,public.current_canteen_id()) on conflict(employee_id,bill_month,bill_year) do update set billing_start_date=excluded.billing_start_date,billing_end_date=excluded.billing_end_date,days_ordered=excluded.days_ordered,food_total=excluded.food_total,guest_food_total=excluded.guest_food_total,admin_added_total=excluded.admin_added_total,total=excluded.total,published=true,published_at=excluded.published_at,updated_at=excluded.updated_at returning * into v_bill;
select coalesce(sum(amount),0) into v_paid from public.bill_payments where bill_id=v_bill.id and employee_id=v_bill.employee_id and canteen_id=v_bill.canteen_id and status='paid';
select coalesce(sum(amount),0) into v_pending from public.bill_payments where bill_id=v_bill.id and employee_id=v_bill.employee_id and canteen_id=v_bill.canteen_id and status='pending_verification';
v_requestable:=greatest(v_total-v_paid-v_pending,0);select coalesce(max(request_sequence),0)+1 into v_seq from public.bill_payments where bill_id=v_bill.id;
if v_requestable>0 then v_id=gen_random_uuid();v_ref='GoCanteen-'||p_year||'-'||lpad(p_month::text,2,'0')||'-'||left(v_bill.employee_id::text,8)||'-B'||v_seq||'-'||left(v_id::text,8);insert into public.bill_payments(id,bill_id,employee_id,amount,status,created_at,updated_at,canteen_id,payment_reference,covered_through,request_sequence) values(v_id,v_bill.id,v_bill.employee_id,v_requestable,'unpaid',v_now,v_now,v_bill.canteen_id,v_ref,v_bill.billing_end_date,v_seq);end if;return v_bill;end;$$;
revoke all on function public.publish_employee_bill(uuid,integer,integer,numeric,numeric,numeric,integer,date,date) from public;grant execute on function public.publish_employee_bill(uuid,integer,integer,numeric,numeric,numeric,integer,date,date) to authenticated;

drop function if exists public.confirm_bill_payment(uuid);
create or replace function public.confirm_bill_payment(p_payment_id uuid) returns public.bill_payments language plpgsql security definer set search_path=public as $$ declare v public.bill_payments%rowtype;begin select * into v from public.bill_payments where id=p_payment_id and employee_id=auth.uid() and canteen_id=public.current_canteen_id();if not found then raise exception 'Payment request not found or not accessible';end if;if v.status='pending_verification' then return v;end if;if v.status not in ('unpaid','not_received','rejected') then raise exception 'Payment request is not payable in its current status';end if;update public.bill_payments set status='pending_verification',confirmed_at=now(),updated_at=now() where id=v.id returning * into v;return v;end;$$;
revoke all on function public.confirm_bill_payment(uuid) from public;grant execute on function public.confirm_bill_payment(uuid) to authenticated;

create or replace function public.set_bill_payment_status(p_payment_id uuid,p_status text) returns public.bill_payments language plpgsql security definer set search_path=public as $$ declare v_admin public.profiles%rowtype;v public.bill_payments%rowtype;v_status text:=case when p_status='not_received' then 'rejected' else p_status end;begin select * into v_admin from public.profiles where id=auth.uid() and role='admin' and status='active' and canteen_id=public.current_canteen_id();if not found then raise exception 'Admin authorization required';end if;if v_status not in ('paid','rejected') then raise exception 'Invalid payment status';end if;select * into v from public.bill_payments where id=p_payment_id and canteen_id=public.current_canteen_id();if not found then raise exception 'Payment record not found';end if;if v.status<>'pending_verification' then raise exception 'Only pending verification payments can be resolved';end if;update public.bill_payments set status=v_status,approved_at=case when v_status='paid' then now() else null end,approved_by=case when v_status='paid' then auth.uid() else null end,updated_at=now() where id=v.id returning * into v;insert into public.notifications(recipient_id,notification_type,title,message,payload,created_at,canteen_id) values(v.employee_id,'payment_status_updated',case when v_status='paid' then 'Payment Received' else 'Payment Rejected' end,case when v_status='paid' then 'Your payment has been verified as received.' else 'Your payment was not received. Please make the outstanding payment again.' end,jsonb_build_object('bill_id',v.bill_id,'payment_id',v.id,'status',v_status,'amount',v.amount,'payment_reference',v.payment_reference),now(),v.canteen_id);return v;end;$$;
