-- Publishing is strictly scoped to the selected calendar month.
-- The RPC ignores caller-supplied rolling/arbitrary dates and derives the
-- authoritative range from p_month/p_year and the current calendar date.
create or replace function public.publish_employee_bill(p_employee_id uuid,p_month integer,p_year integer,p_food_total numeric,p_admin_added_total numeric,p_guest_food_total numeric default 0,p_days_ordered integer default 0,p_billing_start_date date default null,p_billing_end_date date default null) returns public.monthly_bills language plpgsql security definer set search_path to '' as $function$
declare v_now timestamptz:=now(); v_admin public.profiles%rowtype; v_employee public.profiles%rowtype; v_settings public.payment_settings%rowtype; v_bill public.monthly_bills%rowtype; v_month_start date:=make_date(p_year,p_month,1); v_calendar_month_start date; v_today date; v_start date; v_end date; v_month_end date; v_food numeric:=0; v_guest numeric:=0; v_admin_added numeric:=0; v_total numeric:=0; v_covered numeric:=0; v_new numeric:=0; v_last timestamptz; v_seq integer; v_id uuid; v_ref text;
begin
 if p_month<1 or p_month>12 then raise exception 'Invalid billing month'; end if; if p_year<1 then raise exception 'Invalid billing year'; end if;
 v_month_start:=make_date(p_year,p_month,1); v_today:=(now() at time zone current_setting('TIMEZONE'))::date; v_calendar_month_start:=date_trunc('month',v_today)::date; v_month_end:=(v_month_start+interval '1 month - 1 day')::date;
 if v_month_start>v_calendar_month_start then raise exception 'Future month cannot be published'; end if;
 if v_month_start=v_calendar_month_start then v_start:=v_month_start; v_end:=v_today; else v_start:=v_month_start; v_end:=v_month_end; end if;
 select * into v_admin from public.profiles where id=auth.uid() and role='admin' and status='active' and canteen_id=public.current_canteen_id(); if not found or not public.has_admin_permission('bills') then raise exception 'Bill management permission required'; end if;
 select * into v_employee from public.profiles where id=p_employee_id and role='employee' and status='active' and canteen_id=public.current_canteen_id(); if not found then raise exception 'Member not found or is not active in current canteen'; end if;
 perform pg_advisory_xact_lock(hashtext(format('gocanteen-bill-publish:%s:%s:%s:%s',public.current_canteen_id(),p_employee_id,p_month,p_year)));
 if not public.bill_publish_window_open(p_month,p_year) then raise exception 'Publishing available after the employee order window closes.'; end if;
 select * into v_settings from public.payment_settings where canteen_id=public.current_canteen_id() limit 1;
 select coalesce(sum(coalesce(oi.line_total,oi.quantity*oi.unit_price)) filter(where oi.item_source='employee'),0),coalesce(sum(coalesce(oi.line_total,oi.quantity*oi.unit_price)) filter(where oi.item_source='guest'),0) into v_food,v_guest from public.orders o join public.order_items oi on oi.order_id=o.id where o.employee_id=p_employee_id and o.canteen_id=public.current_canteen_id() and o.status='active' and o.ordered_for between v_start and v_end;
 select coalesce(sum(a.amount),0) into v_admin_added from public.employee_adjustments a where a.employee_id=p_employee_id and a.canteen_id=public.current_canteen_id() and a.adjustment_date between v_start and v_end;
 v_total:=greatest(v_food,0)+greatest(v_guest,0)+greatest(v_admin_added,0);
 select * into v_bill from public.monthly_bills where employee_id=p_employee_id and bill_month=p_month and bill_year=p_year and canteen_id=public.current_canteen_id() for update;
 if found then v_covered:=coalesce((select sum(p.amount) from public.bill_payments p where p.bill_id=v_bill.id and p.employee_id=p_employee_id and p.canteen_id=public.current_canteen_id()),0); v_last:=(select max(coalesce(p.covered_through_at,p.created_at)) from public.bill_payments p where p.bill_id=v_bill.id and p.employee_id=p_employee_id and p.canteen_id=public.current_canteen_id()); end if;
 v_new:=greatest(v_total-coalesce(v_covered,0),0); if v_last is not null and v_new<=0 then raise exception 'No new amount since the last publication'; end if; if v_last is null and v_total<=0 then raise exception 'No payable amount available'; end if;
 insert into public.monthly_bills(employee_id,bill_month,bill_year,billing_start_date,billing_end_date,days_ordered,food_total,guest_food_total,admin_added_total,total,published,published_at,updated_at,canteen_id,upi_name,upi_id,upi_number,member_name_snapshot,member_mobile_snapshot) values(p_employee_id,p_month,p_year,v_start,v_end,greatest(coalesce(p_days_ordered,0),0),v_food+v_guest,v_guest,v_admin_added,v_total,true,v_now,v_now,public.current_canteen_id(),nullif(trim(v_settings.upi_name),''),nullif(trim(v_settings.upi_id),''),nullif(trim(v_settings.upi_number),''),v_employee.full_name,v_employee.mobile_number) on conflict(employee_id,bill_month,bill_year) do update set billing_start_date=excluded.billing_start_date,billing_end_date=excluded.billing_end_date,days_ordered=excluded.days_ordered,food_total=excluded.food_total,guest_food_total=excluded.guest_food_total,admin_added_total=excluded.admin_added_total,total=excluded.total,published=true,published_at=excluded.published_at,updated_at=excluded.updated_at,upi_name=excluded.upi_name,upi_id=excluded.upi_id,upi_number=excluded.upi_number,member_name_snapshot=coalesce(public.monthly_bills.member_name_snapshot,excluded.member_name_snapshot),member_mobile_snapshot=coalesce(public.monthly_bills.member_mobile_snapshot,excluded.member_mobile_snapshot) returning * into v_bill;
 v_new:=greatest(v_total-coalesce((select sum(p.amount) from public.bill_payments p where p.bill_id=v_bill.id and p.employee_id=p_employee_id and p.canteen_id=public.current_canteen_id()),0),0); select coalesce(max(request_sequence),0)+1 into v_seq from public.bill_payments where bill_id=v_bill.id; v_id=gen_random_uuid(); v_ref='GoCanteen-'||p_year||'-'||lpad(p_month::text,2,'0')||'-'||left(v_bill.employee_id::text,8)||'-B'||v_seq||'-'||left(v_id::text,8);
 insert into public.bill_payments(id,bill_id,employee_id,amount,status,created_at,updated_at,canteen_id,payment_reference,covered_through,covered_through_at,request_sequence,upi_name,upi_id,upi_number,member_name_snapshot,member_mobile_snapshot) values(v_id,v_bill.id,v_bill.employee_id,v_new,'unpaid',v_now,v_now,v_bill.canteen_id,v_ref,v_end,v_now,v_seq,v_bill.upi_name,v_bill.upi_id,v_bill.upi_number,v_bill.member_name_snapshot,v_bill.member_mobile_snapshot);
 return v_bill; end; $function$;
